github_ci:
  - .github/**/*

strimzi-operator:
  - strimzi-cluster-operator/**/*

kafka:
  - kafka/**/*

kafka-topic:
  - kafka/kafkatopic/**/*

kafka-user:
  - kafka/kafkauser/**/*

clients:
  - clients/**/*

metrics:
  - metrics/**/*
