apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: replicator-carter
spec:
  version: 3.2.0
  replicas: 3
  connectCluster: "heimdall"
  clusters:
    - alias: "anubis"
      bootstrapServers: anubis-kafka-bootstrap:9093
      tls:
        trustedCertificates:
          - secretName: anubis-cluster-ca-cert
            certificate: ca.crt
      authentication:
        type: tls
        certificateAndKey:
          secretName: superuser
          certificate: user.crt
          key: user.key
    - alias: "heimdall"
      bootstrapServers: heimdall-kafka-automation-bootstrap-strimzi-kafka.apps.worker-02.strimzi.app-services-dev.net:443
      tls:
        trustedCertificates:
          # This secret must be copied from target cluster to source cluster where mm2 lives to properly access target Kafka
          - secretName: heimdall-cluster-ca-cert
            certificate: ca.crt
      # This secret must be copied from target cluster to source cluster where mm2 lives to properly access target Kafka
      authentication:
        type: tls
        certificateAndKey:
          secretName: superuser-heimdall
          certificate: user.crt
          key: user.key
      config:
        # -1 means it will use the default replication factor configured in the broker
        config.storage.replication.factor: -1
        offset.storage.replication.factor: -1
        status.storage.replication.factor: -1
  mirrors:
    - sourceCluster: "anubis"
      targetCluster: "heimdall"
      sourceConnector:
        config:
          replication.factor: 3
          offset-syncs.topic.replication.factor: 3
          sync.topic.acls.enabled: "false"
      heartbeatConnector:
        config:
          heartbeats.topic.replication.factor: 3
      checkpointConnector:
        config:
          checkpoints.topic.replication.factor: 3
      topicsPattern: ".*"
      groupsPattern: ".*"
  logging:
    type: inline
    loggers:
      root.logger: DEBUG
