apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-canary
  namespace: strimzi-kafka
  labels:
    app: strimzi-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strimzi-canary
  template:
    metadata:
      labels:
        app: strimzi-canary
    spec:
      serviceAccountName: strimzi-canary
      containers:
        - name: strimzi-canary
          image: quay.io/strimzi/canary@sha256:aa53a6bf49403b2fb616048fcc736eab50dae58fbaff3f19783d44775dadd69b
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: anubis-kafka-bootstrap.strimzi-kafka.svc:9093
            - name: RECONCILE_INTERVAL_MS
              value: "10000"
            - name: EXPECTED_CLUSTER_SIZE
              value: "5"
            - name: TOPIC
              value: "__strimzi_canary"
            - name: TLS_ENABLED
              value: "true"
            - name: TLS_CA_CERT
              value: /tmp/tls-ca-cert/ca.crt
            - name: TLS_CLIENT_CERT
              value: /tmp/client-cert/user.crt
            - name: TLS_CLIENT_KEY
              value: /tmp/client-cert/user.key
            - name: KAFKA_VERSION
              value: "3.0.0"
            - name: SARAMA_LOG_ENABLED
              value: "true"
            - name: VERBOSITY_LOG_LEVEL
              value: "1"
            - name: TLS_INSECURE_SKIP_VERIFY
              value: "true"
          livenessProbe:
            httpGet:
              path: /liveness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              memory: "64Mi"
              cpu: "100m"
            requests:
              memory: "64Mi"
              cpu: "100m"
          volumeMounts:
            - mountPath: /tmp/tls-ca-cert
              name: anubis-cluster-ca
            - mountPath: /tmp/client-cert
              name: client-cert
          ports:
            - containerPort: 8080
              name: metrics
      volumes:
        - name: anubis-cluster-ca
          secret:
            secretName: anubis-cluster-ca-cert
        - name: client-cert
          secret:
            secretName: canary
  strategy:
    type: Recreate
