apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: co-config-volume
          configMap:
            name: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/strimzi/operator@sha256:b8ba0e1918f154887f37994568b9daf90eb20ba9b7bcd86d82ec33db30695fe8
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              # we want to have cluster-wide operator
              value: "*"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: quay.io/strimzi/kafka@sha256:4b4a9e621054402c8a9c2294bf043f8c005141329c7c822fe74caa53ff5dee1d
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: quay.io/strimzi/kafka@sha256:4b4a9e621054402c8a9c2294bf043f8c005141329c7c822fe74caa53ff5dee1d
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:4b4a9e621054402c8a9c2294bf043f8c005141329c7c822fe74caa53ff5dee1d
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:4b4a9e621054402c8a9c2294bf043f8c005141329c7c822fe74caa53ff5dee1d
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:74c0ae1c6c9e7a407c20f09a8c46ea255af1c794200014eb57cf3885e174cb61
                3.0.1=quay.io/strimzi/kafka@sha256:804f88a13c44b424d2a4a443aeedc503d90904e9cd6b8a933fc960e0cccd8e23
                3.1.0=quay.io/strimzi/kafka@sha256:4b4a9e621054402c8a9c2294bf043f8c005141329c7c822fe74caa53ff5dee1d
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:74c0ae1c6c9e7a407c20f09a8c46ea255af1c794200014eb57cf3885e174cb61
                3.0.1=quay.io/strimzi/kafka@sha256:804f88a13c44b424d2a4a443aeedc503d90904e9cd6b8a933fc960e0cccd8e23
                3.1.0=quay.io/strimzi/kafka@sha256:4b4a9e621054402c8a9c2294bf043f8c005141329c7c822fe74caa53ff5dee1d
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:74c0ae1c6c9e7a407c20f09a8c46ea255af1c794200014eb57cf3885e174cb61
                3.0.1=quay.io/strimzi/kafka@sha256:804f88a13c44b424d2a4a443aeedc503d90904e9cd6b8a933fc960e0cccd8e23
                3.1.0=quay.io/strimzi/kafka@sha256:4b4a9e621054402c8a9c2294bf043f8c005141329c7c822fe74caa53ff5dee1d
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:74c0ae1c6c9e7a407c20f09a8c46ea255af1c794200014eb57cf3885e174cb61
                3.0.1=quay.io/strimzi/kafka@sha256:804f88a13c44b424d2a4a443aeedc503d90904e9cd6b8a933fc960e0cccd8e23
                3.1.0=quay.io/strimzi/kafka@sha256:4b4a9e621054402c8a9c2294bf043f8c005141329c7c822fe74caa53ff5dee1d
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:b8ba0e1918f154887f37994568b9daf90eb20ba9b7bcd86d82ec33db30695fe8
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:b8ba0e1918f154887f37994568b9daf90eb20ba9b7bcd86d82ec33db30695fe8
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/strimzi/operator@sha256:b8ba0e1918f154887f37994568b9daf90eb20ba9b7bcd86d82ec33db30695fe8
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge@sha256:e34be514c27a13aeca14a192c0f22041c8dab64d65abbf21070dbfc13f36c671
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: quay.io/strimzi/jmxtrans@sha256:df7f35e7ae9d8e02a1907902e29f58b1c80e681d633c71fa51f494c5dcc461ec
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: quay.io/strimzi/kaniko-executor@sha256:544c4987f7f3ca558b04e9ef4357be204f088212b7b5b9ed0f909401a8bc5238
            - name: STRIMZI_DEFAULT_MAVEN_BUILDER
              value: quay.io/strimzi/maven-builder@sha256:819eddec716ac224b3034017ab827bf3d5a0c0dfbde04093757603498080352d
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FEATURE_GATES
              value: "+UseStrimziPodSets"
            - name: STRIMZI_LOG_LEVEL
              value: "DEBUG"
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 384Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodetype
                    operator: In
                    values:
                      - infra
  strategy:
    type: Recreate
