apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: co-config-volume
          configMap:
            name: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/strimzi/operator@sha256:e586375ed4949d62ad4ea85028ad0808fc53af1388c07db0ed247a898995fd3b
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              # we want to have cluster-wide operator
              value: "*"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: quay.io/strimzi/kafka@sha256:79da68ca6accfccf1caf0c60d39a965ed7fc296ba9dbd350068cef3663a7d3d1
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: quay.io/strimzi/kafka@sha256:79da68ca6accfccf1caf0c60d39a965ed7fc296ba9dbd350068cef3663a7d3d1
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:79da68ca6accfccf1caf0c60d39a965ed7fc296ba9dbd350068cef3663a7d3d1
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:79da68ca6accfccf1caf0c60d39a965ed7fc296ba9dbd350068cef3663a7d3d1
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:14f44d662c7e17a2cfd871c56fb3c70c6d813bb8ab3e3b4daa1e5935d483cbeb
                2.8.1=quay.io/strimzi/kafka@sha256:ca7edcaf31ec8c57ff4762f245194a133ef2f8a09be3961ef98e2d163295ecd6
                3.0.0=quay.io/strimzi/kafka@sha256:79da68ca6accfccf1caf0c60d39a965ed7fc296ba9dbd350068cef3663a7d3d1
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:14f44d662c7e17a2cfd871c56fb3c70c6d813bb8ab3e3b4daa1e5935d483cbeb
                2.8.1=quay.io/strimzi/kafka@sha256:ca7edcaf31ec8c57ff4762f245194a133ef2f8a09be3961ef98e2d163295ecd6
                3.0.0=quay.io/strimzi/kafka@sha256:79da68ca6accfccf1caf0c60d39a965ed7fc296ba9dbd350068cef3663a7d3d1
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:14f44d662c7e17a2cfd871c56fb3c70c6d813bb8ab3e3b4daa1e5935d483cbeb
                2.8.1=quay.io/strimzi/kafka@sha256:ca7edcaf31ec8c57ff4762f245194a133ef2f8a09be3961ef98e2d163295ecd6
                3.0.0=quay.io/strimzi/kafka@sha256:79da68ca6accfccf1caf0c60d39a965ed7fc296ba9dbd350068cef3663a7d3d1
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:14f44d662c7e17a2cfd871c56fb3c70c6d813bb8ab3e3b4daa1e5935d483cbeb
                2.8.1=quay.io/strimzi/kafka@sha256:ca7edcaf31ec8c57ff4762f245194a133ef2f8a09be3961ef98e2d163295ecd6
                3.0.0=quay.io/strimzi/kafka@sha256:79da68ca6accfccf1caf0c60d39a965ed7fc296ba9dbd350068cef3663a7d3d1
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:e586375ed4949d62ad4ea85028ad0808fc53af1388c07db0ed247a898995fd3b
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:e586375ed4949d62ad4ea85028ad0808fc53af1388c07db0ed247a898995fd3b
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/strimzi/operator@sha256:e586375ed4949d62ad4ea85028ad0808fc53af1388c07db0ed247a898995fd3b
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge@sha256:9b29b3528dbd0a5819a43c4a8d0373c9a0f632618b1d62fcef21b2f37ca3b73b
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: quay.io/strimzi/jmxtrans@sha256:b8f62211978aa1061825823af0986dbc9ed9bcc04375f5a899b90f90c60b6d6c
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: quay.io/strimzi/kaniko-executor@sha256:a07ebe6600d6baba09980abdde2931b3b6abd2f75aeb2cac5c6a2d22a37aa807
            - name: STRIMZI_DEFAULT_MAVEN_BUILDER
              value: quay.io/strimzi/maven-builder@sha256:fb8d8461a3db34a4dca8be8b2831f8e975df969edb088936aed0b7e9a963c820
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FEATURE_GATES
              value: ""
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 384Mi
  strategy:
    type: Recreate
