apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: co-config-volume
          configMap:
            name: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/strimzi/operator@sha256:79d859a207f14f188ab8d56723cc42308e8bdb4fc45ccee51134abf9faba4571
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              # we want to have cluster-wide operator
              value: "*"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: quay.io/strimzi/kafka@sha256:44503dcbd522c3570514f90c56bab8f6579b4eb807e5570709f32f50b5ca887b
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: quay.io/strimzi/kafka@sha256:44503dcbd522c3570514f90c56bab8f6579b4eb807e5570709f32f50b5ca887b
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:44503dcbd522c3570514f90c56bab8f6579b4eb807e5570709f32f50b5ca887b
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:44503dcbd522c3570514f90c56bab8f6579b4eb807e5570709f32f50b5ca887b
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:c5b367d782096c69257bc696578c8666a5c2f1db93fa99abc1d87ba2716d20c7
                3.1.0=quay.io/strimzi/kafka@sha256:44503dcbd522c3570514f90c56bab8f6579b4eb807e5570709f32f50b5ca887b
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:c5b367d782096c69257bc696578c8666a5c2f1db93fa99abc1d87ba2716d20c7
                3.1.0=quay.io/strimzi/kafka@sha256:44503dcbd522c3570514f90c56bab8f6579b4eb807e5570709f32f50b5ca887b
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:c5b367d782096c69257bc696578c8666a5c2f1db93fa99abc1d87ba2716d20c7
                3.1.0=quay.io/strimzi/kafka@sha256:44503dcbd522c3570514f90c56bab8f6579b4eb807e5570709f32f50b5ca887b
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:c5b367d782096c69257bc696578c8666a5c2f1db93fa99abc1d87ba2716d20c7
                3.1.0=quay.io/strimzi/kafka@sha256:44503dcbd522c3570514f90c56bab8f6579b4eb807e5570709f32f50b5ca887b
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:79d859a207f14f188ab8d56723cc42308e8bdb4fc45ccee51134abf9faba4571
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:79d859a207f14f188ab8d56723cc42308e8bdb4fc45ccee51134abf9faba4571
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/strimzi/operator@sha256:79d859a207f14f188ab8d56723cc42308e8bdb4fc45ccee51134abf9faba4571
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge@sha256:189c5bc236b4cd49f21f8032db1fe6d024dc4eb749959ac1543e4ab031ae7cb8
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: quay.io/strimzi/jmxtrans@sha256:9b69840534c8630f8a80b05e5e0c75ec0620042cfdbc16825f40ae4910ae34b0
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: quay.io/strimzi/kaniko-executor@sha256:a07ebe6600d6baba09980abdde2931b3b6abd2f75aeb2cac5c6a2d22a37aa807
            - name: STRIMZI_DEFAULT_MAVEN_BUILDER
              value: quay.io/strimzi/maven-builder@sha256:5a27d512e048cb237238fef1cedb561f3be685a34feb6cf368d4f75d2843a743
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FEATURE_GATES
              value: ""
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 384Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodetype
                    operator: In
                    values:
                      - infra
  strategy:
    type: Recreate
