apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: co-config-volume
          configMap:
            name: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/strimzi/operator@sha256:9e65e5a4b4eaae8e44ea020c3aadff52439049c0e88269eb54a946ad60575e11
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              # we want to have cluster-wide operator
              value: "*"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: quay.io/strimzi/kafka@sha256:6071bbfe118253072faff601254ee29b1c7437fab7b096ef50ff7aa9978f0f7a
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: quay.io/strimzi/kafka@sha256:6071bbfe118253072faff601254ee29b1c7437fab7b096ef50ff7aa9978f0f7a
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:6071bbfe118253072faff601254ee29b1c7437fab7b096ef50ff7aa9978f0f7a
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:6071bbfe118253072faff601254ee29b1c7437fab7b096ef50ff7aa9978f0f7a
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:2877eb6173cb0e03c930ceac9a0cfbcfb93ef206144496e5777b226b84ebb570
                2.8.1=quay.io/strimzi/kafka@sha256:cba992dbe022ed9ba36e44c572ae2e591b9b89476dddbcd3f38b13b1197a5c0a
                3.0.0=quay.io/strimzi/kafka@sha256:6071bbfe118253072faff601254ee29b1c7437fab7b096ef50ff7aa9978f0f7a
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:2877eb6173cb0e03c930ceac9a0cfbcfb93ef206144496e5777b226b84ebb570
                2.8.1=quay.io/strimzi/kafka@sha256:cba992dbe022ed9ba36e44c572ae2e591b9b89476dddbcd3f38b13b1197a5c0a
                3.0.0=quay.io/strimzi/kafka@sha256:6071bbfe118253072faff601254ee29b1c7437fab7b096ef50ff7aa9978f0f7a
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:2877eb6173cb0e03c930ceac9a0cfbcfb93ef206144496e5777b226b84ebb570
                2.8.1=quay.io/strimzi/kafka@sha256:cba992dbe022ed9ba36e44c572ae2e591b9b89476dddbcd3f38b13b1197a5c0a
                3.0.0=quay.io/strimzi/kafka@sha256:6071bbfe118253072faff601254ee29b1c7437fab7b096ef50ff7aa9978f0f7a
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:2877eb6173cb0e03c930ceac9a0cfbcfb93ef206144496e5777b226b84ebb570
                2.8.1=quay.io/strimzi/kafka@sha256:cba992dbe022ed9ba36e44c572ae2e591b9b89476dddbcd3f38b13b1197a5c0a
                3.0.0=quay.io/strimzi/kafka@sha256:6071bbfe118253072faff601254ee29b1c7437fab7b096ef50ff7aa9978f0f7a
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:9e65e5a4b4eaae8e44ea020c3aadff52439049c0e88269eb54a946ad60575e11
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:9e65e5a4b4eaae8e44ea020c3aadff52439049c0e88269eb54a946ad60575e11
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/strimzi/operator@sha256:9e65e5a4b4eaae8e44ea020c3aadff52439049c0e88269eb54a946ad60575e11
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge@sha256:85d4c88fe24218007dfcde2d3bebc5a290084bcee414dfa4ff5899e294d452f3
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: quay.io/strimzi/jmxtrans@sha256:5b039ee24fcdf8e9c6b0c1eaec13ad9cea9b07d5f61c8839dbc8e203239f703c
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: quay.io/strimzi/kaniko-executor@sha256:19b934353e409c72b7e71ad9018ed7ba4505682b81da87fb99c7b9dffdb4372a
            - name: STRIMZI_DEFAULT_MAVEN_BUILDER
              value: quay.io/strimzi/maven-builder@sha256:e1e3f921797da977b0fc0ca9ec52416957a55e60aa08e6a57b8182f71a70000d
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FEATURE_GATES
              value: ""
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 384Mi
  strategy:
    type: Recreate
