apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: co-config-volume
          configMap:
            name: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/strimzi/operator@sha256:c5579df3118b3e5e8d65826bbd8a3cccb1985d72052e629eb97518b9d32e2fb4
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              # we want to have cluster-wide operator
              value: "*"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: quay.io/strimzi/kafka@sha256:1f3874430a79581049bc83c8c34fd1678a0e01cb28248377ed981d4bafcade76
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: quay.io/strimzi/kafka@sha256:1f3874430a79581049bc83c8c34fd1678a0e01cb28248377ed981d4bafcade76
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:1f3874430a79581049bc83c8c34fd1678a0e01cb28248377ed981d4bafcade76
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:1f3874430a79581049bc83c8c34fd1678a0e01cb28248377ed981d4bafcade76
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:6b013663511173b56b1321de1f82544348f6ea2976eadd65ce24d6ea68f7f1e0
                3.0.1=quay.io/strimzi/kafka@sha256:563256305a9ead289fc331a756fbeb8113c58a81f4e93eaf6330957f8edc236c
                3.1.0=quay.io/strimzi/kafka@sha256:1f3874430a79581049bc83c8c34fd1678a0e01cb28248377ed981d4bafcade76
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:6b013663511173b56b1321de1f82544348f6ea2976eadd65ce24d6ea68f7f1e0
                3.0.1=quay.io/strimzi/kafka@sha256:563256305a9ead289fc331a756fbeb8113c58a81f4e93eaf6330957f8edc236c
                3.1.0=quay.io/strimzi/kafka@sha256:1f3874430a79581049bc83c8c34fd1678a0e01cb28248377ed981d4bafcade76
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:6b013663511173b56b1321de1f82544348f6ea2976eadd65ce24d6ea68f7f1e0
                3.0.1=quay.io/strimzi/kafka@sha256:563256305a9ead289fc331a756fbeb8113c58a81f4e93eaf6330957f8edc236c
                3.1.0=quay.io/strimzi/kafka@sha256:1f3874430a79581049bc83c8c34fd1678a0e01cb28248377ed981d4bafcade76
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:6b013663511173b56b1321de1f82544348f6ea2976eadd65ce24d6ea68f7f1e0
                3.0.1=quay.io/strimzi/kafka@sha256:563256305a9ead289fc331a756fbeb8113c58a81f4e93eaf6330957f8edc236c
                3.1.0=quay.io/strimzi/kafka@sha256:1f3874430a79581049bc83c8c34fd1678a0e01cb28248377ed981d4bafcade76
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:c5579df3118b3e5e8d65826bbd8a3cccb1985d72052e629eb97518b9d32e2fb4
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:c5579df3118b3e5e8d65826bbd8a3cccb1985d72052e629eb97518b9d32e2fb4
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/strimzi/operator@sha256:c5579df3118b3e5e8d65826bbd8a3cccb1985d72052e629eb97518b9d32e2fb4
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge@sha256:cbaa086a0466b6a3130bbe8a241950e7a23b75329bfa661a9678204e176f1938
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: quay.io/strimzi/jmxtrans@sha256:426bdb51622e796a34c3b17f0972a58d7befe7f1d5ae5ba0df2af4b06ec7661d
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: quay.io/strimzi/kaniko-executor@sha256:f17e8ee327ca966f82bac6a0a2ba2f7fa50dba1418b2a4c93740b809c40fce41
            - name: STRIMZI_DEFAULT_MAVEN_BUILDER
              value: quay.io/strimzi/maven-builder@sha256:b8d740b1daf9e98ba105bc276a25a16953f33f396cd0ae124fb99441df6c72f2
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FEATURE_GATES
              value: ""
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 384Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodetype
                    operator: In
                    values:
                      - infra
  strategy:
    type: Recreate
