apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: co-config-volume
          configMap:
            name: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/strimzi/operator@sha256:b26f3b16ce9295e5c7453004eb6a737ca2aef02d525a3ecacd766e95e536aee3
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              # we want to have cluster-wide operator
              value: "*"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: quay.io/strimzi/kafka@sha256:5d178121fefbc47c131ae44a2a2e53ad2d446f9e8a3a33e632665eb02534077e
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: quay.io/strimzi/kafka@sha256:5d178121fefbc47c131ae44a2a2e53ad2d446f9e8a3a33e632665eb02534077e
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:5d178121fefbc47c131ae44a2a2e53ad2d446f9e8a3a33e632665eb02534077e
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:5d178121fefbc47c131ae44a2a2e53ad2d446f9e8a3a33e632665eb02534077e
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:b7ea49e72d6781a2b00609183d0a9fd87bd786642063a509f7df41e4e9b2dc1a
                3.0.1=quay.io/strimzi/kafka@sha256:914a01f851d83f6cfb2b2efad5c315e299440e4d5bd750112e43042b1057a3d5
                3.1.0=quay.io/strimzi/kafka@sha256:5d178121fefbc47c131ae44a2a2e53ad2d446f9e8a3a33e632665eb02534077e
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:b7ea49e72d6781a2b00609183d0a9fd87bd786642063a509f7df41e4e9b2dc1a
                3.0.1=quay.io/strimzi/kafka@sha256:914a01f851d83f6cfb2b2efad5c315e299440e4d5bd750112e43042b1057a3d5
                3.1.0=quay.io/strimzi/kafka@sha256:5d178121fefbc47c131ae44a2a2e53ad2d446f9e8a3a33e632665eb02534077e
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:b7ea49e72d6781a2b00609183d0a9fd87bd786642063a509f7df41e4e9b2dc1a
                3.0.1=quay.io/strimzi/kafka@sha256:914a01f851d83f6cfb2b2efad5c315e299440e4d5bd750112e43042b1057a3d5
                3.1.0=quay.io/strimzi/kafka@sha256:5d178121fefbc47c131ae44a2a2e53ad2d446f9e8a3a33e632665eb02534077e
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:b7ea49e72d6781a2b00609183d0a9fd87bd786642063a509f7df41e4e9b2dc1a
                3.0.1=quay.io/strimzi/kafka@sha256:914a01f851d83f6cfb2b2efad5c315e299440e4d5bd750112e43042b1057a3d5
                3.1.0=quay.io/strimzi/kafka@sha256:5d178121fefbc47c131ae44a2a2e53ad2d446f9e8a3a33e632665eb02534077e
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:b26f3b16ce9295e5c7453004eb6a737ca2aef02d525a3ecacd766e95e536aee3
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:b26f3b16ce9295e5c7453004eb6a737ca2aef02d525a3ecacd766e95e536aee3
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/strimzi/operator@sha256:b26f3b16ce9295e5c7453004eb6a737ca2aef02d525a3ecacd766e95e536aee3
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge@sha256:cbaa086a0466b6a3130bbe8a241950e7a23b75329bfa661a9678204e176f1938
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: quay.io/strimzi/jmxtrans@sha256:f815e59dcd084f01d9ebab9ba905df04e53fede679039b06506a156c3e63bcba
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: quay.io/strimzi/kaniko-executor@sha256:f17e8ee327ca966f82bac6a0a2ba2f7fa50dba1418b2a4c93740b809c40fce41
            - name: STRIMZI_DEFAULT_MAVEN_BUILDER
              value: quay.io/strimzi/maven-builder@sha256:1d0fe021b054669da1b73e0a2d7d0d2ded5efe58316d400871bf92b8abb0560b
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FEATURE_GATES
              value: ""
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 384Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodetype
                    operator: In
                    values:
                      - infra
  strategy:
    type: Recreate
