apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: co-config-volume
          configMap:
            name: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/strimzi/operator@sha256:0e45466166aa5c98d0c130506f9603578635c4a3899789f3cf8ded7d06fcc62a
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              # we want to have cluster-wide operator
              value: "*"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: quay.io/strimzi/kafka@sha256:7a8142b6cd83a4e324ec381a62da064bcc6d8dc9fc77e672ab62a8ef91ce34cb
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: quay.io/strimzi/kafka@sha256:7a8142b6cd83a4e324ec381a62da064bcc6d8dc9fc77e672ab62a8ef91ce34cb
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:7a8142b6cd83a4e324ec381a62da064bcc6d8dc9fc77e672ab62a8ef91ce34cb
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:c9b0b3176d3069842ca7c2c0ba4dc9146d5ab372d6eff14754f65d8f3fddcad3
                3.0.1=quay.io/strimzi/kafka@sha256:fd6fbaac869486acb0a7224d97857c5a7b6c67ff1a3169e3f69726b4f3026915
                3.1.0=quay.io/strimzi/kafka@sha256:7a8142b6cd83a4e324ec381a62da064bcc6d8dc9fc77e672ab62a8ef91ce34cb
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:c9b0b3176d3069842ca7c2c0ba4dc9146d5ab372d6eff14754f65d8f3fddcad3
                3.0.1=quay.io/strimzi/kafka@sha256:fd6fbaac869486acb0a7224d97857c5a7b6c67ff1a3169e3f69726b4f3026915
                3.1.0=quay.io/strimzi/kafka@sha256:7a8142b6cd83a4e324ec381a62da064bcc6d8dc9fc77e672ab62a8ef91ce34cb
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:c9b0b3176d3069842ca7c2c0ba4dc9146d5ab372d6eff14754f65d8f3fddcad3
                3.0.1=quay.io/strimzi/kafka@sha256:fd6fbaac869486acb0a7224d97857c5a7b6c67ff1a3169e3f69726b4f3026915
                3.1.0=quay.io/strimzi/kafka@sha256:7a8142b6cd83a4e324ec381a62da064bcc6d8dc9fc77e672ab62a8ef91ce34cb
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:c9b0b3176d3069842ca7c2c0ba4dc9146d5ab372d6eff14754f65d8f3fddcad3
                3.0.1=quay.io/strimzi/kafka@sha256:fd6fbaac869486acb0a7224d97857c5a7b6c67ff1a3169e3f69726b4f3026915
                3.1.0=quay.io/strimzi/kafka@sha256:7a8142b6cd83a4e324ec381a62da064bcc6d8dc9fc77e672ab62a8ef91ce34cb
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:0e45466166aa5c98d0c130506f9603578635c4a3899789f3cf8ded7d06fcc62a
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:0e45466166aa5c98d0c130506f9603578635c4a3899789f3cf8ded7d06fcc62a
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/strimzi/operator@sha256:0e45466166aa5c98d0c130506f9603578635c4a3899789f3cf8ded7d06fcc62a
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge@sha256:e34be514c27a13aeca14a192c0f22041c8dab64d65abbf21070dbfc13f36c671
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: quay.io/strimzi/jmxtrans@sha256:1e40982d94470ea6238086403a3980ef19b66b94cad556cbe07c541c8f8e325a
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: quay.io/strimzi/kaniko-executor@sha256:544c4987f7f3ca558b04e9ef4357be204f088212b7b5b9ed0f909401a8bc5238
            - name: STRIMZI_DEFAULT_MAVEN_BUILDER
              value: quay.io/strimzi/maven-builder@sha256:e9af660f939698ad1904aade80509e7356225bd5ed443eac468dd149aa09339f
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FEATURE_GATES
              value: "+UseStrimziPodSets"
            - name: STRIMZI_LOG_LEVEL
              value: "DEBUG"
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 384Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodetype
                    operator: In
                    values:
                      - infra
  strategy:
    type: Recreate
