apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: co-config-volume
          configMap:
            name: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/strimzi/operator@sha256:ae8c8417a31c88a0093bccc4f06695deffd06fdf5afc8db64424f05d143b0621
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              # we want to have cluster-wide operator
              value: "*"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: quay.io/strimzi/kafka@sha256:142bdc4a953eb61777f9ba740a89dd0b1225b100d01c069558b05b9ff1fcb1ed
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: quay.io/strimzi/kafka@sha256:142bdc4a953eb61777f9ba740a89dd0b1225b100d01c069558b05b9ff1fcb1ed
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:142bdc4a953eb61777f9ba740a89dd0b1225b100d01c069558b05b9ff1fcb1ed
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:142bdc4a953eb61777f9ba740a89dd0b1225b100d01c069558b05b9ff1fcb1ed
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:ec29c5928335fc9cc201b1589d4e7235f98bb338068e6c9e94f9ea33d63f1d80
                2.8.1=quay.io/strimzi/kafka@sha256:dc60dddd3fd6770ac080f77cdd82003dde744c161ae025ebecfdd409020efa6a
                3.0.0=quay.io/strimzi/kafka@sha256:142bdc4a953eb61777f9ba740a89dd0b1225b100d01c069558b05b9ff1fcb1ed
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:ec29c5928335fc9cc201b1589d4e7235f98bb338068e6c9e94f9ea33d63f1d80
                2.8.1=quay.io/strimzi/kafka@sha256:dc60dddd3fd6770ac080f77cdd82003dde744c161ae025ebecfdd409020efa6a
                3.0.0=quay.io/strimzi/kafka@sha256:142bdc4a953eb61777f9ba740a89dd0b1225b100d01c069558b05b9ff1fcb1ed
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:ec29c5928335fc9cc201b1589d4e7235f98bb338068e6c9e94f9ea33d63f1d80
                2.8.1=quay.io/strimzi/kafka@sha256:dc60dddd3fd6770ac080f77cdd82003dde744c161ae025ebecfdd409020efa6a
                3.0.0=quay.io/strimzi/kafka@sha256:142bdc4a953eb61777f9ba740a89dd0b1225b100d01c069558b05b9ff1fcb1ed
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:ec29c5928335fc9cc201b1589d4e7235f98bb338068e6c9e94f9ea33d63f1d80
                2.8.1=quay.io/strimzi/kafka@sha256:dc60dddd3fd6770ac080f77cdd82003dde744c161ae025ebecfdd409020efa6a
                3.0.0=quay.io/strimzi/kafka@sha256:142bdc4a953eb61777f9ba740a89dd0b1225b100d01c069558b05b9ff1fcb1ed
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:ae8c8417a31c88a0093bccc4f06695deffd06fdf5afc8db64424f05d143b0621
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:ae8c8417a31c88a0093bccc4f06695deffd06fdf5afc8db64424f05d143b0621
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/strimzi/operator@sha256:ae8c8417a31c88a0093bccc4f06695deffd06fdf5afc8db64424f05d143b0621
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge@sha256:9b29b3528dbd0a5819a43c4a8d0373c9a0f632618b1d62fcef21b2f37ca3b73b
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: quay.io/strimzi/jmxtrans@sha256:704939e88b4b79c3ee486746eb7fd4bec948f009477585d91480b6de588242c5
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: quay.io/strimzi/kaniko-executor@sha256:a07ebe6600d6baba09980abdde2931b3b6abd2f75aeb2cac5c6a2d22a37aa807
            - name: STRIMZI_DEFAULT_MAVEN_BUILDER
              value: quay.io/strimzi/maven-builder@sha256:5353986579233e598edd81e132c52939451bf8d0069c614be84f3f0d6a1cd869
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FEATURE_GATES
              value: ""
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 384Mi
  strategy:
    type: Recreate
