apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  namespace: strimzi-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: co-config-volume
          configMap:
            name: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/strimzi/operator@sha256:a0b5fd49aa88a4fc1bf47743b2d42bd20188d0586cc10288351013cec2e203bc
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              # we want to have cluster-wide operator
              value: "*"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: quay.io/strimzi/kafka@sha256:04a61403cf30d36e857497cc404ce876c8ad972b91463776c8f39b93a86fd024
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: quay.io/strimzi/kafka@sha256:04a61403cf30d36e857497cc404ce876c8ad972b91463776c8f39b93a86fd024
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:04a61403cf30d36e857497cc404ce876c8ad972b91463776c8f39b93a86fd024
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:04a61403cf30d36e857497cc404ce876c8ad972b91463776c8f39b93a86fd024
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:d4bc8948126b9ea4790ca3476dabe8124fc8954a655d18d8c06be7b7e77eca50
                2.8.1=quay.io/strimzi/kafka@sha256:9662bd76dc986709227077081e3d62e99273938a4ac1a0e1db8758ec2a6b1d04
                3.0.0=quay.io/strimzi/kafka@sha256:04a61403cf30d36e857497cc404ce876c8ad972b91463776c8f39b93a86fd024
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:d4bc8948126b9ea4790ca3476dabe8124fc8954a655d18d8c06be7b7e77eca50
                2.8.1=quay.io/strimzi/kafka@sha256:9662bd76dc986709227077081e3d62e99273938a4ac1a0e1db8758ec2a6b1d04
                3.0.0=quay.io/strimzi/kafka@sha256:04a61403cf30d36e857497cc404ce876c8ad972b91463776c8f39b93a86fd024
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:d4bc8948126b9ea4790ca3476dabe8124fc8954a655d18d8c06be7b7e77eca50
                2.8.1=quay.io/strimzi/kafka@sha256:9662bd76dc986709227077081e3d62e99273938a4ac1a0e1db8758ec2a6b1d04
                3.0.0=quay.io/strimzi/kafka@sha256:04a61403cf30d36e857497cc404ce876c8ad972b91463776c8f39b93a86fd024
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:d4bc8948126b9ea4790ca3476dabe8124fc8954a655d18d8c06be7b7e77eca50
                2.8.1=quay.io/strimzi/kafka@sha256:9662bd76dc986709227077081e3d62e99273938a4ac1a0e1db8758ec2a6b1d04
                3.0.0=quay.io/strimzi/kafka@sha256:04a61403cf30d36e857497cc404ce876c8ad972b91463776c8f39b93a86fd024
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:a0b5fd49aa88a4fc1bf47743b2d42bd20188d0586cc10288351013cec2e203bc
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:a0b5fd49aa88a4fc1bf47743b2d42bd20188d0586cc10288351013cec2e203bc
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/strimzi/operator@sha256:a0b5fd49aa88a4fc1bf47743b2d42bd20188d0586cc10288351013cec2e203bc
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge@sha256:daa97f0c6341620b59eb4b30a11cda5f10edb619dc1ccfe97e393c49af088406
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: quay.io/strimzi/jmxtrans@sha256:ab315441f15af9a44507e751acf04311101eb188fb962d96cf63237d885f8c14
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: quay.io/strimzi/kaniko-executor@sha256:19b934353e409c72b7e71ad9018ed7ba4505682b81da87fb99c7b9dffdb4372a
            - name: STRIMZI_DEFAULT_MAVEN_BUILDER
              value: quay.io/strimzi/maven-builder@sha256:464e6ae724575ece118eb2213003aabd8eddf16852d0ecab550f0ae4e0d8acd7
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FEATURE_GATES
              value: ""
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 384Mi
  strategy:
    type: Recreate
