apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: co-config-volume
          configMap:
            name: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/strimzi/operator@sha256:96aa027af6caefec3ddbbf713aa59477ec56f4ef7d5fae1bccb43b3db5b3c480
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              # we want to have cluster-wide operator
              value: "*"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: quay.io/strimzi/kafka@sha256:ead432d42b0c16bdf81bd8ddbd2c6dcdd4384a280097c3e8d8eb20ee6b00b559
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: quay.io/strimzi/kafka@sha256:ead432d42b0c16bdf81bd8ddbd2c6dcdd4384a280097c3e8d8eb20ee6b00b559
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:ead432d42b0c16bdf81bd8ddbd2c6dcdd4384a280097c3e8d8eb20ee6b00b559
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                3.1.0=quay.io/strimzi/kafka@sha256:012ec282463c71ef9262552850a2f42ec3f0b8f844e8463b40297fd7fda00516
                3.1.1=quay.io/strimzi/kafka@sha256:881fc13fbd998683a22ee603134f53e881efd5c23cc1471b7e6066902854e36e
                3.2.0=quay.io/strimzi/kafka@sha256:ead432d42b0c16bdf81bd8ddbd2c6dcdd4384a280097c3e8d8eb20ee6b00b559
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                3.1.0=quay.io/strimzi/kafka@sha256:012ec282463c71ef9262552850a2f42ec3f0b8f844e8463b40297fd7fda00516
                3.1.1=quay.io/strimzi/kafka@sha256:881fc13fbd998683a22ee603134f53e881efd5c23cc1471b7e6066902854e36e
                3.2.0=quay.io/strimzi/kafka@sha256:ead432d42b0c16bdf81bd8ddbd2c6dcdd4384a280097c3e8d8eb20ee6b00b559
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                3.1.0=quay.io/strimzi/kafka@sha256:012ec282463c71ef9262552850a2f42ec3f0b8f844e8463b40297fd7fda00516
                3.1.1=quay.io/strimzi/kafka@sha256:881fc13fbd998683a22ee603134f53e881efd5c23cc1471b7e6066902854e36e
                3.2.0=quay.io/strimzi/kafka@sha256:ead432d42b0c16bdf81bd8ddbd2c6dcdd4384a280097c3e8d8eb20ee6b00b559
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                3.1.0=quay.io/strimzi/kafka@sha256:012ec282463c71ef9262552850a2f42ec3f0b8f844e8463b40297fd7fda00516
                3.1.1=quay.io/strimzi/kafka@sha256:881fc13fbd998683a22ee603134f53e881efd5c23cc1471b7e6066902854e36e
                3.2.0=quay.io/strimzi/kafka@sha256:ead432d42b0c16bdf81bd8ddbd2c6dcdd4384a280097c3e8d8eb20ee6b00b559
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:96aa027af6caefec3ddbbf713aa59477ec56f4ef7d5fae1bccb43b3db5b3c480
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:96aa027af6caefec3ddbbf713aa59477ec56f4ef7d5fae1bccb43b3db5b3c480
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/strimzi/operator@sha256:96aa027af6caefec3ddbbf713aa59477ec56f4ef7d5fae1bccb43b3db5b3c480
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge@sha256:1dc429113d3d2026bc958af9f6637b5269752d48569bb68a73772c91a8db08e3
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: quay.io/strimzi/jmxtrans@sha256:08b23b67aec2845d2aa14b2c308ba1e4e912936994219e2c81915d63434ac829
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: quay.io/strimzi/kaniko-executor@sha256:544c4987f7f3ca558b04e9ef4357be204f088212b7b5b9ed0f909401a8bc5238
            - name: STRIMZI_DEFAULT_MAVEN_BUILDER
              value: quay.io/strimzi/maven-builder@sha256:a7b12543cbab2195801780ac8358d86b027f2e1e1949f09df8f42811059c98e7
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FEATURE_GATES
              value: "+UseStrimziPodSets"
            - name: STRIMZI_LOG_LEVEL
              value: "DEBUG"
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 384Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodetype
                    operator: In
                    values:
                      - infra
  strategy:
    type: Recreate
