apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: co-config-volume
          configMap:
            name: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/strimzi/operator@sha256:90d5c0c21ac05ed264fe57d69ae9daa730209749f26e78a364aac0670b8059d5
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              # we want to have cluster-wide operator
              value: "*"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: quay.io/strimzi/kafka@sha256:226cad6ec31cc9a900fb89f5886ab15ba5da91f3a9cbb07b2731e9e515392660
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: quay.io/strimzi/kafka@sha256:226cad6ec31cc9a900fb89f5886ab15ba5da91f3a9cbb07b2731e9e515392660
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:226cad6ec31cc9a900fb89f5886ab15ba5da91f3a9cbb07b2731e9e515392660
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:226cad6ec31cc9a900fb89f5886ab15ba5da91f3a9cbb07b2731e9e515392660
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:4208f757533bd04016430c893131f07d17063e66e340e5b78786b434c74cf73b
                2.8.1=quay.io/strimzi/kafka@sha256:ec6f89dbef0084a13523219c410d66cbb2982c432689d4093c2227123d5b0004
                3.0.0=quay.io/strimzi/kafka@sha256:226cad6ec31cc9a900fb89f5886ab15ba5da91f3a9cbb07b2731e9e515392660
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:4208f757533bd04016430c893131f07d17063e66e340e5b78786b434c74cf73b
                2.8.1=quay.io/strimzi/kafka@sha256:ec6f89dbef0084a13523219c410d66cbb2982c432689d4093c2227123d5b0004
                3.0.0=quay.io/strimzi/kafka@sha256:226cad6ec31cc9a900fb89f5886ab15ba5da91f3a9cbb07b2731e9e515392660
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:4208f757533bd04016430c893131f07d17063e66e340e5b78786b434c74cf73b
                2.8.1=quay.io/strimzi/kafka@sha256:ec6f89dbef0084a13523219c410d66cbb2982c432689d4093c2227123d5b0004
                3.0.0=quay.io/strimzi/kafka@sha256:226cad6ec31cc9a900fb89f5886ab15ba5da91f3a9cbb07b2731e9e515392660
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:4208f757533bd04016430c893131f07d17063e66e340e5b78786b434c74cf73b
                2.8.1=quay.io/strimzi/kafka@sha256:ec6f89dbef0084a13523219c410d66cbb2982c432689d4093c2227123d5b0004
                3.0.0=quay.io/strimzi/kafka@sha256:226cad6ec31cc9a900fb89f5886ab15ba5da91f3a9cbb07b2731e9e515392660
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:90d5c0c21ac05ed264fe57d69ae9daa730209749f26e78a364aac0670b8059d5
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:90d5c0c21ac05ed264fe57d69ae9daa730209749f26e78a364aac0670b8059d5
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/strimzi/operator@sha256:90d5c0c21ac05ed264fe57d69ae9daa730209749f26e78a364aac0670b8059d5
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge@sha256:85d4c88fe24218007dfcde2d3bebc5a290084bcee414dfa4ff5899e294d452f3
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: quay.io/strimzi/jmxtrans@sha256:f17a1a939e8e7d18894102c754931abcf040bb4370648dee7cbf9b88453323f6
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: quay.io/strimzi/kaniko-executor@sha256:19b934353e409c72b7e71ad9018ed7ba4505682b81da87fb99c7b9dffdb4372a
            - name: STRIMZI_DEFAULT_MAVEN_BUILDER
              value: quay.io/strimzi/maven-builder@sha256:0fb518e5c568b0fff69700f8f733f3b1a18b73e9963e5d30267696cfa793aee4
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FEATURE_GATES
              value: ""
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 384Mi
  strategy:
    type: Recreate
