apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: co-config-volume
          configMap:
            name: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/strimzi/operator@sha256:6dc0e7c7578b64d6b3db6ddbc16152f162cd9a29d38037070c57eb77fd136d1d
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              # we want to have cluster-wide operator
              value: "*"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: quay.io/strimzi/kafka@sha256:48f5c5e6cd2f51efba0c016f0dc7dba3141199c23ef7b750e8d325b005a811af
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: quay.io/strimzi/kafka@sha256:48f5c5e6cd2f51efba0c016f0dc7dba3141199c23ef7b750e8d325b005a811af
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:48f5c5e6cd2f51efba0c016f0dc7dba3141199c23ef7b750e8d325b005a811af
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                3.1.0=quay.io/strimzi/kafka@sha256:491a95c622b93627ae51839febc82ab0a0406feafa616f7c1c6c2ec9022fec48
                3.1.1=quay.io/strimzi/kafka@sha256:ac30a3ae95474102490621349e2f342f29831ca77ce551d013a4b0580a2d0ada
                3.2.0=quay.io/strimzi/kafka@sha256:48f5c5e6cd2f51efba0c016f0dc7dba3141199c23ef7b750e8d325b005a811af
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                3.1.0=quay.io/strimzi/kafka@sha256:491a95c622b93627ae51839febc82ab0a0406feafa616f7c1c6c2ec9022fec48
                3.1.1=quay.io/strimzi/kafka@sha256:ac30a3ae95474102490621349e2f342f29831ca77ce551d013a4b0580a2d0ada
                3.2.0=quay.io/strimzi/kafka@sha256:48f5c5e6cd2f51efba0c016f0dc7dba3141199c23ef7b750e8d325b005a811af
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                3.1.0=quay.io/strimzi/kafka@sha256:491a95c622b93627ae51839febc82ab0a0406feafa616f7c1c6c2ec9022fec48
                3.1.1=quay.io/strimzi/kafka@sha256:ac30a3ae95474102490621349e2f342f29831ca77ce551d013a4b0580a2d0ada
                3.2.0=quay.io/strimzi/kafka@sha256:48f5c5e6cd2f51efba0c016f0dc7dba3141199c23ef7b750e8d325b005a811af
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                3.1.0=quay.io/strimzi/kafka@sha256:491a95c622b93627ae51839febc82ab0a0406feafa616f7c1c6c2ec9022fec48
                3.1.1=quay.io/strimzi/kafka@sha256:ac30a3ae95474102490621349e2f342f29831ca77ce551d013a4b0580a2d0ada
                3.2.0=quay.io/strimzi/kafka@sha256:48f5c5e6cd2f51efba0c016f0dc7dba3141199c23ef7b750e8d325b005a811af
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:6dc0e7c7578b64d6b3db6ddbc16152f162cd9a29d38037070c57eb77fd136d1d
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:6dc0e7c7578b64d6b3db6ddbc16152f162cd9a29d38037070c57eb77fd136d1d
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/strimzi/operator@sha256:6dc0e7c7578b64d6b3db6ddbc16152f162cd9a29d38037070c57eb77fd136d1d
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge@sha256:af8504d7f0b462c820fabc914b4e04ce49a18c39a6e2168ac62effe7e2e34edb
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: quay.io/strimzi/jmxtrans@sha256:11ec36e4f80226b2d612614a20af98d39fad15971f849683d7a7bdaf93695eed
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: quay.io/strimzi/kaniko-executor@sha256:544c4987f7f3ca558b04e9ef4357be204f088212b7b5b9ed0f909401a8bc5238
            - name: STRIMZI_DEFAULT_MAVEN_BUILDER
              value: quay.io/strimzi/maven-builder@sha256:c1ce5f31673ac55fb2e61df96cc59edec57163789aea895ed651a06c62dac9e6
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FEATURE_GATES
              value: "+UseStrimziPodSets"
            - name: STRIMZI_LOG_LEVEL
              value: "DEBUG"
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 384Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodetype
                    operator: In
                    values:
                      - infra
  strategy:
    type: Recreate
