apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  namespace: strimzi-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: co-config-volume
          configMap:
            name: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/strimzi/operator@sha256:a948355ea259388062c52b90faf7a1241d97cc79338ed7cb4e5ee629b72d54a3
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              # we want to have cluster-wide operator
              value: "*"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: quay.io/strimzi/kafka@sha256:088035e89da9f70d8b5d28af5a8cb23a7439c27069a294216356830b0be43671
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: quay.io/strimzi/kafka@sha256:088035e89da9f70d8b5d28af5a8cb23a7439c27069a294216356830b0be43671
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:088035e89da9f70d8b5d28af5a8cb23a7439c27069a294216356830b0be43671
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:088035e89da9f70d8b5d28af5a8cb23a7439c27069a294216356830b0be43671
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:2dbb9df3f5f16cbb5ee122c2e9a0fac266ae95cd2c4230280aae64aebd4a39e1
                2.8.1=quay.io/strimzi/kafka@sha256:bc4a5f8836585fae8efc53e4b46d882ab078db0564959b2ab296b370beab7643
                3.0.0=quay.io/strimzi/kafka@sha256:088035e89da9f70d8b5d28af5a8cb23a7439c27069a294216356830b0be43671
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:2dbb9df3f5f16cbb5ee122c2e9a0fac266ae95cd2c4230280aae64aebd4a39e1
                2.8.1=quay.io/strimzi/kafka@sha256:bc4a5f8836585fae8efc53e4b46d882ab078db0564959b2ab296b370beab7643
                3.0.0=quay.io/strimzi/kafka@sha256:088035e89da9f70d8b5d28af5a8cb23a7439c27069a294216356830b0be43671
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:2dbb9df3f5f16cbb5ee122c2e9a0fac266ae95cd2c4230280aae64aebd4a39e1
                2.8.1=quay.io/strimzi/kafka@sha256:bc4a5f8836585fae8efc53e4b46d882ab078db0564959b2ab296b370beab7643
                3.0.0=quay.io/strimzi/kafka@sha256:088035e89da9f70d8b5d28af5a8cb23a7439c27069a294216356830b0be43671
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:2dbb9df3f5f16cbb5ee122c2e9a0fac266ae95cd2c4230280aae64aebd4a39e1
                2.8.1=quay.io/strimzi/kafka@sha256:bc4a5f8836585fae8efc53e4b46d882ab078db0564959b2ab296b370beab7643
                3.0.0=quay.io/strimzi/kafka@sha256:088035e89da9f70d8b5d28af5a8cb23a7439c27069a294216356830b0be43671
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:a948355ea259388062c52b90faf7a1241d97cc79338ed7cb4e5ee629b72d54a3
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:a948355ea259388062c52b90faf7a1241d97cc79338ed7cb4e5ee629b72d54a3
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/strimzi/operator@sha256:a948355ea259388062c52b90faf7a1241d97cc79338ed7cb4e5ee629b72d54a3
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge@sha256:85d4c88fe24218007dfcde2d3bebc5a290084bcee414dfa4ff5899e294d452f3
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: quay.io/strimzi/jmxtrans@sha256:aee1a41c792b7e5e060ca03252be95304250bec9edbbb8670943be26eddeab91
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: quay.io/strimzi/kaniko-executor@sha256:19b934353e409c72b7e71ad9018ed7ba4505682b81da87fb99c7b9dffdb4372a
            - name: STRIMZI_DEFAULT_MAVEN_BUILDER
              value: quay.io/strimzi/maven-builder@sha256:ebdf9a0beb47f16e43c73475f251b35be6bc3a3ba819dbcb1cbb2349eecedb05
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FEATURE_GATES
              value: ""
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 384Mi
  strategy:
    type: Recreate
