apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  namespace: strimzi-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: co-config-volume
          configMap:
            name: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/strimzi/operator@sha256:a9de90969dd1c2ba96949e6d353eef08da8025e384201c9517096ac1ac9ba302
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              # we want to have cluster-wide operator
              value: "*"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: quay.io/strimzi/kafka@sha256:1450f32730ade434e08447ca8ed30b1335bb22fb651a00452434eecba91c4aa8
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: quay.io/strimzi/kafka@sha256:1450f32730ade434e08447ca8ed30b1335bb22fb651a00452434eecba91c4aa8
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:1450f32730ade434e08447ca8ed30b1335bb22fb651a00452434eecba91c4aa8
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:1450f32730ade434e08447ca8ed30b1335bb22fb651a00452434eecba91c4aa8
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:fe9b4fd127f61738fde842507298e2832eed9c407b61fc860d483715cdc333a3
                2.8.1=quay.io/strimzi/kafka@sha256:0d9e3e65d1a2dcbafa24cd1088ea509f428ba558a5f1a6d138e5bb2a8d788c3b
                3.0.0=quay.io/strimzi/kafka@sha256:1450f32730ade434e08447ca8ed30b1335bb22fb651a00452434eecba91c4aa8
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:fe9b4fd127f61738fde842507298e2832eed9c407b61fc860d483715cdc333a3
                2.8.1=quay.io/strimzi/kafka@sha256:0d9e3e65d1a2dcbafa24cd1088ea509f428ba558a5f1a6d138e5bb2a8d788c3b
                3.0.0=quay.io/strimzi/kafka@sha256:1450f32730ade434e08447ca8ed30b1335bb22fb651a00452434eecba91c4aa8
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:fe9b4fd127f61738fde842507298e2832eed9c407b61fc860d483715cdc333a3
                2.8.1=quay.io/strimzi/kafka@sha256:0d9e3e65d1a2dcbafa24cd1088ea509f428ba558a5f1a6d138e5bb2a8d788c3b
                3.0.0=quay.io/strimzi/kafka@sha256:1450f32730ade434e08447ca8ed30b1335bb22fb651a00452434eecba91c4aa8
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:fe9b4fd127f61738fde842507298e2832eed9c407b61fc860d483715cdc333a3
                2.8.1=quay.io/strimzi/kafka@sha256:0d9e3e65d1a2dcbafa24cd1088ea509f428ba558a5f1a6d138e5bb2a8d788c3b
                3.0.0=quay.io/strimzi/kafka@sha256:1450f32730ade434e08447ca8ed30b1335bb22fb651a00452434eecba91c4aa8
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:a9de90969dd1c2ba96949e6d353eef08da8025e384201c9517096ac1ac9ba302
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:a9de90969dd1c2ba96949e6d353eef08da8025e384201c9517096ac1ac9ba302
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/strimzi/operator@sha256:a9de90969dd1c2ba96949e6d353eef08da8025e384201c9517096ac1ac9ba302
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge@sha256:8a0ff1dbb9d822e74b601401ea924386aad1ce8771212013038b9f8da5956252
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: quay.io/strimzi/jmxtrans@sha256:885c461b47795ca94b318db6bb54413d0b09fa7c9cce78845015de1ffa6e7953
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: quay.io/strimzi/kaniko-executor@sha256:19b934353e409c72b7e71ad9018ed7ba4505682b81da87fb99c7b9dffdb4372a
            - name: STRIMZI_DEFAULT_MAVEN_BUILDER
              value: quay.io/strimzi/maven-builder@sha256:4b637a86764b01f0428b01155786ecea0746b016ab0350b770aa086dbe3e20b5
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FEATURE_GATES
              value: ""
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 384Mi
  strategy:
    type: Recreate
