apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: co-config-volume
          configMap:
            name: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/strimzi/operator@sha256:9823ffe19f18ce0e3a212385af02733c7c262aae9bcc8c5475706b739fbe2519
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              # we want to have cluster-wide operator
              value: "*"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: quay.io/strimzi/kafka@sha256:6cf23ea7849cf3ca960181cf21f96c12d00776195c27198f939dba62860ca829
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: quay.io/strimzi/kafka@sha256:6cf23ea7849cf3ca960181cf21f96c12d00776195c27198f939dba62860ca829
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:6cf23ea7849cf3ca960181cf21f96c12d00776195c27198f939dba62860ca829
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:6cf23ea7849cf3ca960181cf21f96c12d00776195c27198f939dba62860ca829
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:e277f9befca07bc0bc884b4b0df86410a09068418b0e5183e0652abf4cf625f4
                2.8.1=quay.io/strimzi/kafka@sha256:3acf13a0d9b0681d96aa150d2936b662a7f8f3ead8ea834dfca9270a81c7ab4e
                3.0.0=quay.io/strimzi/kafka@sha256:6cf23ea7849cf3ca960181cf21f96c12d00776195c27198f939dba62860ca829
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:e277f9befca07bc0bc884b4b0df86410a09068418b0e5183e0652abf4cf625f4
                2.8.1=quay.io/strimzi/kafka@sha256:3acf13a0d9b0681d96aa150d2936b662a7f8f3ead8ea834dfca9270a81c7ab4e
                3.0.0=quay.io/strimzi/kafka@sha256:6cf23ea7849cf3ca960181cf21f96c12d00776195c27198f939dba62860ca829
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:e277f9befca07bc0bc884b4b0df86410a09068418b0e5183e0652abf4cf625f4
                2.8.1=quay.io/strimzi/kafka@sha256:3acf13a0d9b0681d96aa150d2936b662a7f8f3ead8ea834dfca9270a81c7ab4e
                3.0.0=quay.io/strimzi/kafka@sha256:6cf23ea7849cf3ca960181cf21f96c12d00776195c27198f939dba62860ca829
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:e277f9befca07bc0bc884b4b0df86410a09068418b0e5183e0652abf4cf625f4
                2.8.1=quay.io/strimzi/kafka@sha256:3acf13a0d9b0681d96aa150d2936b662a7f8f3ead8ea834dfca9270a81c7ab4e
                3.0.0=quay.io/strimzi/kafka@sha256:6cf23ea7849cf3ca960181cf21f96c12d00776195c27198f939dba62860ca829
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:9823ffe19f18ce0e3a212385af02733c7c262aae9bcc8c5475706b739fbe2519
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:9823ffe19f18ce0e3a212385af02733c7c262aae9bcc8c5475706b739fbe2519
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/strimzi/operator@sha256:9823ffe19f18ce0e3a212385af02733c7c262aae9bcc8c5475706b739fbe2519
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge@sha256:6d3aa1f8e77345d19f5d0a826aaff358227cad10f521c1f82460185f80a21e3a
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: quay.io/strimzi/jmxtrans@sha256:cce1381c45961256be72da3ad325defc26511f055abeb879b679714bfc132e62
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: quay.io/strimzi/kaniko-executor@sha256:7a25608bedb32e8bcd1c05a6d117cd67d6ec5221c081a0c9333ca2a286e52f60
            - name: STRIMZI_DEFAULT_MAVEN_BUILDER
              value: quay.io/strimzi/maven-builder@sha256:1c68f8ba7506b43d1377e9a58e20659b39f7694ec3f74fa24d798331a838e4c2
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FEATURE_GATES
              value: ""
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 384Mi
  strategy:
    type: Recreate
