apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: co-config-volume
          configMap:
            name: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/strimzi/operator@sha256:56dff4c5a013aa8b121ee0c761511a6ca3ce4b66d1db008923b69ab5d6b5f3cc
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              # we want to have cluster-wide operator
              value: "*"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: quay.io/strimzi/kafka@sha256:6d4d33bbd4af94a80284a12baf2c4e7adde23461adf90e7ee1790b53fc128546
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: quay.io/strimzi/kafka@sha256:6d4d33bbd4af94a80284a12baf2c4e7adde23461adf90e7ee1790b53fc128546
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:6d4d33bbd4af94a80284a12baf2c4e7adde23461adf90e7ee1790b53fc128546
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                3.1.0=quay.io/strimzi/kafka@sha256:0a215bd37e7936123ef6061da7a275bac8db941b24797174252bc5e181507396
                3.1.1=quay.io/strimzi/kafka@sha256:84d1b89b9c707c12c6df183e0c5c07dbb63c407d56e4263d4f7edaaf22a58eea
                3.2.0=quay.io/strimzi/kafka@sha256:6d4d33bbd4af94a80284a12baf2c4e7adde23461adf90e7ee1790b53fc128546
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                3.1.0=quay.io/strimzi/kafka@sha256:0a215bd37e7936123ef6061da7a275bac8db941b24797174252bc5e181507396
                3.1.1=quay.io/strimzi/kafka@sha256:84d1b89b9c707c12c6df183e0c5c07dbb63c407d56e4263d4f7edaaf22a58eea
                3.2.0=quay.io/strimzi/kafka@sha256:6d4d33bbd4af94a80284a12baf2c4e7adde23461adf90e7ee1790b53fc128546
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                3.1.0=quay.io/strimzi/kafka@sha256:0a215bd37e7936123ef6061da7a275bac8db941b24797174252bc5e181507396
                3.1.1=quay.io/strimzi/kafka@sha256:84d1b89b9c707c12c6df183e0c5c07dbb63c407d56e4263d4f7edaaf22a58eea
                3.2.0=quay.io/strimzi/kafka@sha256:6d4d33bbd4af94a80284a12baf2c4e7adde23461adf90e7ee1790b53fc128546
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                3.1.0=quay.io/strimzi/kafka@sha256:0a215bd37e7936123ef6061da7a275bac8db941b24797174252bc5e181507396
                3.1.1=quay.io/strimzi/kafka@sha256:84d1b89b9c707c12c6df183e0c5c07dbb63c407d56e4263d4f7edaaf22a58eea
                3.2.0=quay.io/strimzi/kafka@sha256:6d4d33bbd4af94a80284a12baf2c4e7adde23461adf90e7ee1790b53fc128546
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:56dff4c5a013aa8b121ee0c761511a6ca3ce4b66d1db008923b69ab5d6b5f3cc
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:56dff4c5a013aa8b121ee0c761511a6ca3ce4b66d1db008923b69ab5d6b5f3cc
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/strimzi/operator@sha256:56dff4c5a013aa8b121ee0c761511a6ca3ce4b66d1db008923b69ab5d6b5f3cc
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge@sha256:f7acfce3600d4af2ed5ee0a834123c179ae238a02e564dfcba649e98d74b19a8
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: quay.io/strimzi/jmxtrans@sha256:85d0bb644d0c27b036a2ac4534f40aecc723e452856feb4ef5662c727c49fce1
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: quay.io/strimzi/kaniko-executor@sha256:544c4987f7f3ca558b04e9ef4357be204f088212b7b5b9ed0f909401a8bc5238
            - name: STRIMZI_DEFAULT_MAVEN_BUILDER
              value: quay.io/strimzi/maven-builder@sha256:7e09570b8ec2201be11e7e6b6a2b390f20607e5c71958b843be8671c052e6dd1
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FEATURE_GATES
              value: "+UseStrimziPodSets"
            - name: STRIMZI_LOG_LEVEL
              value: "DEBUG"
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 384Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodetype
                    operator: In
                    values:
                      - infra
  strategy:
    type: Recreate
