apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: co-config-volume
          configMap:
            name: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/strimzi/operator@sha256:c4cf19072e5d859472fe4afdd96fecefecce1e0be1b199f371130cd03f0113a1
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              # we want to have cluster-wide operator
              value: "*"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: quay.io/strimzi/kafka@sha256:9276b006b8ba3c9ad3e5434a15ef10316b4bcb4a6184ea56a4ed4b13bf91bfc7
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: quay.io/strimzi/kafka@sha256:9276b006b8ba3c9ad3e5434a15ef10316b4bcb4a6184ea56a4ed4b13bf91bfc7
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:9276b006b8ba3c9ad3e5434a15ef10316b4bcb4a6184ea56a4ed4b13bf91bfc7
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:9276b006b8ba3c9ad3e5434a15ef10316b4bcb4a6184ea56a4ed4b13bf91bfc7
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:9e86a62d43346b34b14bb21a6249adc1ad869540bd8996afef198613b34c0e0c
                2.8.1=quay.io/strimzi/kafka@sha256:04d1fb0b5933db372370539cc49f7a88f8fd9f7315b8c8ec257e41c0a66588b3
                3.0.0=quay.io/strimzi/kafka@sha256:9276b006b8ba3c9ad3e5434a15ef10316b4bcb4a6184ea56a4ed4b13bf91bfc7
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:9e86a62d43346b34b14bb21a6249adc1ad869540bd8996afef198613b34c0e0c
                2.8.1=quay.io/strimzi/kafka@sha256:04d1fb0b5933db372370539cc49f7a88f8fd9f7315b8c8ec257e41c0a66588b3
                3.0.0=quay.io/strimzi/kafka@sha256:9276b006b8ba3c9ad3e5434a15ef10316b4bcb4a6184ea56a4ed4b13bf91bfc7
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:9e86a62d43346b34b14bb21a6249adc1ad869540bd8996afef198613b34c0e0c
                2.8.1=quay.io/strimzi/kafka@sha256:04d1fb0b5933db372370539cc49f7a88f8fd9f7315b8c8ec257e41c0a66588b3
                3.0.0=quay.io/strimzi/kafka@sha256:9276b006b8ba3c9ad3e5434a15ef10316b4bcb4a6184ea56a4ed4b13bf91bfc7
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:9e86a62d43346b34b14bb21a6249adc1ad869540bd8996afef198613b34c0e0c
                2.8.1=quay.io/strimzi/kafka@sha256:04d1fb0b5933db372370539cc49f7a88f8fd9f7315b8c8ec257e41c0a66588b3
                3.0.0=quay.io/strimzi/kafka@sha256:9276b006b8ba3c9ad3e5434a15ef10316b4bcb4a6184ea56a4ed4b13bf91bfc7
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:c4cf19072e5d859472fe4afdd96fecefecce1e0be1b199f371130cd03f0113a1
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:c4cf19072e5d859472fe4afdd96fecefecce1e0be1b199f371130cd03f0113a1
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/strimzi/operator@sha256:c4cf19072e5d859472fe4afdd96fecefecce1e0be1b199f371130cd03f0113a1
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge@sha256:3c88dcf4d00728025b73b98ae660747cb9d4f564f5f42e772aa85fc1aea86885
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: quay.io/strimzi/jmxtrans@sha256:0783bb911c044f97db8ca87665d08a8e6443a13096f84ae69d8c3b16023a1ba5
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: quay.io/strimzi/kaniko-executor@sha256:a07ebe6600d6baba09980abdde2931b3b6abd2f75aeb2cac5c6a2d22a37aa807
            - name: STRIMZI_DEFAULT_MAVEN_BUILDER
              value: quay.io/strimzi/maven-builder@sha256:76bbe84dac8dba6d6b0057f54642db8bb47480c9656d704d9dfcc2dfb174fcba
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FEATURE_GATES
              value: ""
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 384Mi
  strategy:
    type: Recreate
