apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: co-config-volume
          configMap:
            name: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/strimzi/operator@sha256:2c1ca0817f37d18232b4920924e53cc261d2e792bc084394455ac265aa0b8910
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              # we want to have cluster-wide operator
              value: "*"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: quay.io/strimzi/kafka@sha256:8522594c3ee25737a140c83f28f1321e708f134c160d4c037308b929adeaa9dc
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: quay.io/strimzi/kafka@sha256:8522594c3ee25737a140c83f28f1321e708f134c160d4c037308b929adeaa9dc
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:8522594c3ee25737a140c83f28f1321e708f134c160d4c037308b929adeaa9dc
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                3.1.0=quay.io/strimzi/kafka@sha256:cd1ea7b7812a8df25c92db5535b10020967726809ccee7d6050f2e38d8f5bcd9
                3.1.1=quay.io/strimzi/kafka@sha256:ea41221510cd59fe8cda8e08dfafc04d2f10b434fdae3a8de7ecd39321952d83
                3.2.0=quay.io/strimzi/kafka@sha256:8522594c3ee25737a140c83f28f1321e708f134c160d4c037308b929adeaa9dc
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                3.1.0=quay.io/strimzi/kafka@sha256:cd1ea7b7812a8df25c92db5535b10020967726809ccee7d6050f2e38d8f5bcd9
                3.1.1=quay.io/strimzi/kafka@sha256:ea41221510cd59fe8cda8e08dfafc04d2f10b434fdae3a8de7ecd39321952d83
                3.2.0=quay.io/strimzi/kafka@sha256:8522594c3ee25737a140c83f28f1321e708f134c160d4c037308b929adeaa9dc
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                3.1.0=quay.io/strimzi/kafka@sha256:cd1ea7b7812a8df25c92db5535b10020967726809ccee7d6050f2e38d8f5bcd9
                3.1.1=quay.io/strimzi/kafka@sha256:ea41221510cd59fe8cda8e08dfafc04d2f10b434fdae3a8de7ecd39321952d83
                3.2.0=quay.io/strimzi/kafka@sha256:8522594c3ee25737a140c83f28f1321e708f134c160d4c037308b929adeaa9dc
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                3.1.0=quay.io/strimzi/kafka@sha256:cd1ea7b7812a8df25c92db5535b10020967726809ccee7d6050f2e38d8f5bcd9
                3.1.1=quay.io/strimzi/kafka@sha256:ea41221510cd59fe8cda8e08dfafc04d2f10b434fdae3a8de7ecd39321952d83
                3.2.0=quay.io/strimzi/kafka@sha256:8522594c3ee25737a140c83f28f1321e708f134c160d4c037308b929adeaa9dc
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:2c1ca0817f37d18232b4920924e53cc261d2e792bc084394455ac265aa0b8910
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:2c1ca0817f37d18232b4920924e53cc261d2e792bc084394455ac265aa0b8910
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/strimzi/operator@sha256:2c1ca0817f37d18232b4920924e53cc261d2e792bc084394455ac265aa0b8910
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge@sha256:af8504d7f0b462c820fabc914b4e04ce49a18c39a6e2168ac62effe7e2e34edb
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: quay.io/strimzi/jmxtrans@sha256:3c2ee06c08f284b6b870af48c6abf4737ed2bb27f771a62a2593808b40753836
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: quay.io/strimzi/kaniko-executor@sha256:544c4987f7f3ca558b04e9ef4357be204f088212b7b5b9ed0f909401a8bc5238
            - name: STRIMZI_DEFAULT_MAVEN_BUILDER
              value: quay.io/strimzi/maven-builder@sha256:a88353901770c708fe873a8ce2cfe1f6bfa326ddaecc217980f37149ed9334c8
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FEATURE_GATES
              value: "+UseStrimziPodSets"
            - name: STRIMZI_LOG_LEVEL
              value: "DEBUG"
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 384Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodetype
                    operator: In
                    values:
                      - infra
  strategy:
    type: Recreate
