apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: co-config-volume
          configMap:
            name: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/strimzi/operator@sha256:90daa013e4c3c0212e747b554b9a83ed0e35cdb28545ec03e6bcbb2a3af12175
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              # we want to have cluster-wide operator
              value: "*"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: quay.io/strimzi/kafka@sha256:72ffc5bfc978a85ff18f29d729b114b9fd615e14c649ad832f5cb693dc677730
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: quay.io/strimzi/kafka@sha256:72ffc5bfc978a85ff18f29d729b114b9fd615e14c649ad832f5cb693dc677730
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:72ffc5bfc978a85ff18f29d729b114b9fd615e14c649ad832f5cb693dc677730
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:72ffc5bfc978a85ff18f29d729b114b9fd615e14c649ad832f5cb693dc677730
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:6aec93160f017b2bcc16d1cc9a5792691c37e40ae546b8abaf55c0ae85a7792e
                3.0.1=quay.io/strimzi/kafka@sha256:0c4388dd87465887f6c7647cec6f323e47b85214e3314c5a504654ac7d5c399a
                3.1.0=quay.io/strimzi/kafka@sha256:72ffc5bfc978a85ff18f29d729b114b9fd615e14c649ad832f5cb693dc677730
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:6aec93160f017b2bcc16d1cc9a5792691c37e40ae546b8abaf55c0ae85a7792e
                3.0.1=quay.io/strimzi/kafka@sha256:0c4388dd87465887f6c7647cec6f323e47b85214e3314c5a504654ac7d5c399a
                3.1.0=quay.io/strimzi/kafka@sha256:72ffc5bfc978a85ff18f29d729b114b9fd615e14c649ad832f5cb693dc677730
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:6aec93160f017b2bcc16d1cc9a5792691c37e40ae546b8abaf55c0ae85a7792e
                3.0.1=quay.io/strimzi/kafka@sha256:0c4388dd87465887f6c7647cec6f323e47b85214e3314c5a504654ac7d5c399a
                3.1.0=quay.io/strimzi/kafka@sha256:72ffc5bfc978a85ff18f29d729b114b9fd615e14c649ad832f5cb693dc677730
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:6aec93160f017b2bcc16d1cc9a5792691c37e40ae546b8abaf55c0ae85a7792e
                3.0.1=quay.io/strimzi/kafka@sha256:0c4388dd87465887f6c7647cec6f323e47b85214e3314c5a504654ac7d5c399a
                3.1.0=quay.io/strimzi/kafka@sha256:72ffc5bfc978a85ff18f29d729b114b9fd615e14c649ad832f5cb693dc677730
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:90daa013e4c3c0212e747b554b9a83ed0e35cdb28545ec03e6bcbb2a3af12175
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:90daa013e4c3c0212e747b554b9a83ed0e35cdb28545ec03e6bcbb2a3af12175
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/strimzi/operator@sha256:90daa013e4c3c0212e747b554b9a83ed0e35cdb28545ec03e6bcbb2a3af12175
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge@sha256:e7215c185f09ea556be4060bc4c9c68a904daa4e35cfc2335f0a9abe75997421
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: quay.io/strimzi/jmxtrans@sha256:c3c06cf6daf6f2ce543139eae28bdec6b08e1f6a91e2ac45934908e8bf3df676
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: quay.io/strimzi/kaniko-executor@sha256:f17e8ee327ca966f82bac6a0a2ba2f7fa50dba1418b2a4c93740b809c40fce41
            - name: STRIMZI_DEFAULT_MAVEN_BUILDER
              value: quay.io/strimzi/maven-builder@sha256:03cc0763dec36291f20ff6274ced309f17c1ef45952f1d6b6ac7d659e9639d30
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FEATURE_GATES
              value: "+UseStrimziPodSets"
            - name: STRIMZI_LOG_LEVEL
              value: "DEBUG"
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 2000m
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 384Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodetype
                    operator: In
                    values:
                      - infra
  strategy:
    type: Recreate
