apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: co-config-volume
          configMap:
            name: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/strimzi/operator@sha256:c2669a2e9cf0907952693e3320c9f7d635bc32465807104fc7d615d9043d5232
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              # we want to have cluster-wide operator
              value: "*"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: quay.io/strimzi/kafka@sha256:723d8b101d9e9163905b9547c32e72d81546be7c0feae02b524a4660074511bb
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: quay.io/strimzi/kafka@sha256:723d8b101d9e9163905b9547c32e72d81546be7c0feae02b524a4660074511bb
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:723d8b101d9e9163905b9547c32e72d81546be7c0feae02b524a4660074511bb
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:723d8b101d9e9163905b9547c32e72d81546be7c0feae02b524a4660074511bb
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:8c889369c27f15c2713ffa713262dbbccb4ec8d9cb5ee05b4eadb4478ec6e85c
                3.1.0=quay.io/strimzi/kafka@sha256:723d8b101d9e9163905b9547c32e72d81546be7c0feae02b524a4660074511bb
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:8c889369c27f15c2713ffa713262dbbccb4ec8d9cb5ee05b4eadb4478ec6e85c
                3.1.0=quay.io/strimzi/kafka@sha256:723d8b101d9e9163905b9547c32e72d81546be7c0feae02b524a4660074511bb
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:8c889369c27f15c2713ffa713262dbbccb4ec8d9cb5ee05b4eadb4478ec6e85c
                3.1.0=quay.io/strimzi/kafka@sha256:723d8b101d9e9163905b9547c32e72d81546be7c0feae02b524a4660074511bb
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:8c889369c27f15c2713ffa713262dbbccb4ec8d9cb5ee05b4eadb4478ec6e85c
                3.1.0=quay.io/strimzi/kafka@sha256:723d8b101d9e9163905b9547c32e72d81546be7c0feae02b524a4660074511bb
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:c2669a2e9cf0907952693e3320c9f7d635bc32465807104fc7d615d9043d5232
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:c2669a2e9cf0907952693e3320c9f7d635bc32465807104fc7d615d9043d5232
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/strimzi/operator@sha256:c2669a2e9cf0907952693e3320c9f7d635bc32465807104fc7d615d9043d5232
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge@sha256:27f8e72ef1d2df0fbdbdd83db4578ee6bc8d65864a40b6c91eb7a2d1f64c7a9b
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: quay.io/strimzi/jmxtrans@sha256:d81f585c0bf70802d3ba37d06b93e092f4b59077c783cca541b6567ef9a59e30
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: quay.io/strimzi/kaniko-executor@sha256:a07ebe6600d6baba09980abdde2931b3b6abd2f75aeb2cac5c6a2d22a37aa807
            - name: STRIMZI_DEFAULT_MAVEN_BUILDER
              value: quay.io/strimzi/maven-builder@sha256:ad44e6d6e4e332542c6d772a92260aef86b0e9f9b490b8d664fe57fbe12a7c52
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FEATURE_GATES
              value: ""
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 384Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodetype
                    operator: In
                    values:
                      - infra
  strategy:
    type: Recreate
