apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: co-config-volume
          configMap:
            name: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/strimzi/operator@sha256:5bfd827c2d82ec707310c6d17984674a518b011ac76557211a07478f5589bae7
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              # we want to have cluster-wide operator
              value: "*"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: quay.io/strimzi/kafka@sha256:f07937348d689a1c039cdf74f1e65c5c7af8c0094b8b50f019d425a2c648620b
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: quay.io/strimzi/kafka@sha256:f07937348d689a1c039cdf74f1e65c5c7af8c0094b8b50f019d425a2c648620b
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:f07937348d689a1c039cdf74f1e65c5c7af8c0094b8b50f019d425a2c648620b
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:6c9d155bc362a3ab2e3c872ee7d063ca51a4b8514942829cc03fd32c92a56e76
                3.0.1=quay.io/strimzi/kafka@sha256:b786fcbd51fb865113a4d41e5afd5b9d0af9cd62b731911f55efc88a28363e7f
                3.1.0=quay.io/strimzi/kafka@sha256:f07937348d689a1c039cdf74f1e65c5c7af8c0094b8b50f019d425a2c648620b
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:6c9d155bc362a3ab2e3c872ee7d063ca51a4b8514942829cc03fd32c92a56e76
                3.0.1=quay.io/strimzi/kafka@sha256:b786fcbd51fb865113a4d41e5afd5b9d0af9cd62b731911f55efc88a28363e7f
                3.1.0=quay.io/strimzi/kafka@sha256:f07937348d689a1c039cdf74f1e65c5c7af8c0094b8b50f019d425a2c648620b
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:6c9d155bc362a3ab2e3c872ee7d063ca51a4b8514942829cc03fd32c92a56e76
                3.0.1=quay.io/strimzi/kafka@sha256:b786fcbd51fb865113a4d41e5afd5b9d0af9cd62b731911f55efc88a28363e7f
                3.1.0=quay.io/strimzi/kafka@sha256:f07937348d689a1c039cdf74f1e65c5c7af8c0094b8b50f019d425a2c648620b
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:6c9d155bc362a3ab2e3c872ee7d063ca51a4b8514942829cc03fd32c92a56e76
                3.0.1=quay.io/strimzi/kafka@sha256:b786fcbd51fb865113a4d41e5afd5b9d0af9cd62b731911f55efc88a28363e7f
                3.1.0=quay.io/strimzi/kafka@sha256:f07937348d689a1c039cdf74f1e65c5c7af8c0094b8b50f019d425a2c648620b
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:5bfd827c2d82ec707310c6d17984674a518b011ac76557211a07478f5589bae7
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:5bfd827c2d82ec707310c6d17984674a518b011ac76557211a07478f5589bae7
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/strimzi/operator@sha256:5bfd827c2d82ec707310c6d17984674a518b011ac76557211a07478f5589bae7
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge@sha256:b1bfd695b7e45c399a5699dc68c1406e6f5d1cda0a30fc8cdb9648c91cbbe895
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: quay.io/strimzi/jmxtrans@sha256:8629f7c4cfcf7226bbfb8eba50ed58e9a3d573e7f370e84d87d7f76f772700ae
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: quay.io/strimzi/kaniko-executor@sha256:544c4987f7f3ca558b04e9ef4357be204f088212b7b5b9ed0f909401a8bc5238
            - name: STRIMZI_DEFAULT_MAVEN_BUILDER
              value: quay.io/strimzi/maven-builder@sha256:078b413d05b255502b2d327c03d0c11b5d0c96f9f37fd9f4cc86eee9de9985f5
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FEATURE_GATES
              value: "+UseStrimziPodSets"
            - name: STRIMZI_LOG_LEVEL
              value: "DEBUG"
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 384Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodetype
                    operator: In
                    values:
                      - infra
  strategy:
    type: Recreate
