apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  namespace: strimzi-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: co-config-volume
          configMap:
            name: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/strimzi/operator@sha256:7f4909be91536daedcd50ee10a230a9a33070f9433b87f9a7a6bb12dc7d80831
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              # we want to have cluster-wide operator
              value: "*"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: quay.io/strimzi/kafka@sha256:fcb2bf30e2d1def737468159b57972a594f21e7cf904b9cb9c6630d550c29a00
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: quay.io/strimzi/kafka@sha256:fcb2bf30e2d1def737468159b57972a594f21e7cf904b9cb9c6630d550c29a00
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:fcb2bf30e2d1def737468159b57972a594f21e7cf904b9cb9c6630d550c29a00
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:fcb2bf30e2d1def737468159b57972a594f21e7cf904b9cb9c6630d550c29a00
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:e2bfb28416291fd7fa69c0ba776b35f9a4deb470e61c63645f80dd99775e5a71
                2.8.1=quay.io/strimzi/kafka@sha256:7be5f2c8f544e82408f5223eb20bb2bac73adcf7a68fbc8dcee8b44dc29f28fb
                3.0.0=quay.io/strimzi/kafka@sha256:fcb2bf30e2d1def737468159b57972a594f21e7cf904b9cb9c6630d550c29a00
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:e2bfb28416291fd7fa69c0ba776b35f9a4deb470e61c63645f80dd99775e5a71
                2.8.1=quay.io/strimzi/kafka@sha256:7be5f2c8f544e82408f5223eb20bb2bac73adcf7a68fbc8dcee8b44dc29f28fb
                3.0.0=quay.io/strimzi/kafka@sha256:fcb2bf30e2d1def737468159b57972a594f21e7cf904b9cb9c6630d550c29a00
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:e2bfb28416291fd7fa69c0ba776b35f9a4deb470e61c63645f80dd99775e5a71
                2.8.1=quay.io/strimzi/kafka@sha256:7be5f2c8f544e82408f5223eb20bb2bac73adcf7a68fbc8dcee8b44dc29f28fb
                3.0.0=quay.io/strimzi/kafka@sha256:fcb2bf30e2d1def737468159b57972a594f21e7cf904b9cb9c6630d550c29a00
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:e2bfb28416291fd7fa69c0ba776b35f9a4deb470e61c63645f80dd99775e5a71
                2.8.1=quay.io/strimzi/kafka@sha256:7be5f2c8f544e82408f5223eb20bb2bac73adcf7a68fbc8dcee8b44dc29f28fb
                3.0.0=quay.io/strimzi/kafka@sha256:fcb2bf30e2d1def737468159b57972a594f21e7cf904b9cb9c6630d550c29a00
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:7f4909be91536daedcd50ee10a230a9a33070f9433b87f9a7a6bb12dc7d80831
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:7f4909be91536daedcd50ee10a230a9a33070f9433b87f9a7a6bb12dc7d80831
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/strimzi/operator@sha256:7f4909be91536daedcd50ee10a230a9a33070f9433b87f9a7a6bb12dc7d80831
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge@sha256:9636fd2f9fb221b969b0f62276bdc02815a141ebc90c45af8e13e92faabee419
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: quay.io/strimzi/jmxtrans@sha256:64113e2811d502647fc0a11be8946c62e0603174bacba67b80c9e55f45f1db8a
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: quay.io/strimzi/kaniko-executor@sha256:19b934353e409c72b7e71ad9018ed7ba4505682b81da87fb99c7b9dffdb4372a
            - name: STRIMZI_DEFAULT_MAVEN_BUILDER
              value: quay.io/strimzi/maven-builder@sha256:0cb9e1da6d311df0a1d631a8f3dbb9ffd8dca65eb66b9014ecd1a4e53df548a6
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FEATURE_GATES
              value: ""
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 384Mi
  strategy:
    type: Recreate
