apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: co-config-volume
          configMap:
            name: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/strimzi/operator@sha256:82559d67e4619f4c33982aab81419ec0113b846fc6bbbb6ef13215b64b27d1f5
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              # we want to have cluster-wide operator
              value: "*"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: quay.io/strimzi/kafka@sha256:7d75aed7a6ae32ef7ec947f21122d20124cbe1e3f03fffc71aae166a2f5e9ce8
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: quay.io/strimzi/kafka@sha256:7d75aed7a6ae32ef7ec947f21122d20124cbe1e3f03fffc71aae166a2f5e9ce8
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:7d75aed7a6ae32ef7ec947f21122d20124cbe1e3f03fffc71aae166a2f5e9ce8
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:7d75aed7a6ae32ef7ec947f21122d20124cbe1e3f03fffc71aae166a2f5e9ce8
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:e82460683fa7ad75747a15533785134da50042d9ea6fe5bb17edf56cb80a1bd4
                2.8.1=quay.io/strimzi/kafka@sha256:e2d9ba8990cceef5809cff49c993f36314adcedbc93cd130e8ffdea2ada22b18
                3.0.0=quay.io/strimzi/kafka@sha256:7d75aed7a6ae32ef7ec947f21122d20124cbe1e3f03fffc71aae166a2f5e9ce8
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:e82460683fa7ad75747a15533785134da50042d9ea6fe5bb17edf56cb80a1bd4
                2.8.1=quay.io/strimzi/kafka@sha256:e2d9ba8990cceef5809cff49c993f36314adcedbc93cd130e8ffdea2ada22b18
                3.0.0=quay.io/strimzi/kafka@sha256:7d75aed7a6ae32ef7ec947f21122d20124cbe1e3f03fffc71aae166a2f5e9ce8
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:e82460683fa7ad75747a15533785134da50042d9ea6fe5bb17edf56cb80a1bd4
                2.8.1=quay.io/strimzi/kafka@sha256:e2d9ba8990cceef5809cff49c993f36314adcedbc93cd130e8ffdea2ada22b18
                3.0.0=quay.io/strimzi/kafka@sha256:7d75aed7a6ae32ef7ec947f21122d20124cbe1e3f03fffc71aae166a2f5e9ce8
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                2.8.0=quay.io/strimzi/kafka@sha256:e82460683fa7ad75747a15533785134da50042d9ea6fe5bb17edf56cb80a1bd4
                2.8.1=quay.io/strimzi/kafka@sha256:e2d9ba8990cceef5809cff49c993f36314adcedbc93cd130e8ffdea2ada22b18
                3.0.0=quay.io/strimzi/kafka@sha256:7d75aed7a6ae32ef7ec947f21122d20124cbe1e3f03fffc71aae166a2f5e9ce8
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:82559d67e4619f4c33982aab81419ec0113b846fc6bbbb6ef13215b64b27d1f5
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:82559d67e4619f4c33982aab81419ec0113b846fc6bbbb6ef13215b64b27d1f5
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/strimzi/operator@sha256:82559d67e4619f4c33982aab81419ec0113b846fc6bbbb6ef13215b64b27d1f5
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge@sha256:3c88dcf4d00728025b73b98ae660747cb9d4f564f5f42e772aa85fc1aea86885
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: quay.io/strimzi/jmxtrans@sha256:3392d0821f028fcc901ec4f6342dff91b2fa48a43bf592f5405d15b7db48e83f
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: quay.io/strimzi/kaniko-executor@sha256:a07ebe6600d6baba09980abdde2931b3b6abd2f75aeb2cac5c6a2d22a37aa807
            - name: STRIMZI_DEFAULT_MAVEN_BUILDER
              value: quay.io/strimzi/maven-builder@sha256:a18e7a8ea1010c05cbd9d40c4f8ae2f6ce5ebae737c99b4d8e8e330be0613a83
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FEATURE_GATES
              value: ""
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 384Mi
  strategy:
    type: Recreate
