apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: co-config-volume
          configMap:
            name: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/strimzi/operator@sha256:52f9aa160bdd748f3bf7df52130ff965bec20e0a3f366bdbb7d88736b1c2c79a
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              # we want to have cluster-wide operator
              value: "*"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: quay.io/strimzi/kafka@sha256:ea47e1c0464d1228aa1c373c5961324a0b1bd381521051b21c1e8c569ab96dda
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: quay.io/strimzi/kafka@sha256:ea47e1c0464d1228aa1c373c5961324a0b1bd381521051b21c1e8c569ab96dda
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:ea47e1c0464d1228aa1c373c5961324a0b1bd381521051b21c1e8c569ab96dda
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:a1d253024fc3b975fbe4a4bfd96a62b758058415fc9cc0e0cd058532c243f008
                3.0.1=quay.io/strimzi/kafka@sha256:6e89087be5e41794bb4f82e4b08cf5b584def9fafe28effa390347050b4bd1e8
                3.1.0=quay.io/strimzi/kafka@sha256:ea47e1c0464d1228aa1c373c5961324a0b1bd381521051b21c1e8c569ab96dda
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:a1d253024fc3b975fbe4a4bfd96a62b758058415fc9cc0e0cd058532c243f008
                3.0.1=quay.io/strimzi/kafka@sha256:6e89087be5e41794bb4f82e4b08cf5b584def9fafe28effa390347050b4bd1e8
                3.1.0=quay.io/strimzi/kafka@sha256:ea47e1c0464d1228aa1c373c5961324a0b1bd381521051b21c1e8c569ab96dda
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:a1d253024fc3b975fbe4a4bfd96a62b758058415fc9cc0e0cd058532c243f008
                3.0.1=quay.io/strimzi/kafka@sha256:6e89087be5e41794bb4f82e4b08cf5b584def9fafe28effa390347050b4bd1e8
                3.1.0=quay.io/strimzi/kafka@sha256:ea47e1c0464d1228aa1c373c5961324a0b1bd381521051b21c1e8c569ab96dda
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:a1d253024fc3b975fbe4a4bfd96a62b758058415fc9cc0e0cd058532c243f008
                3.0.1=quay.io/strimzi/kafka@sha256:6e89087be5e41794bb4f82e4b08cf5b584def9fafe28effa390347050b4bd1e8
                3.1.0=quay.io/strimzi/kafka@sha256:ea47e1c0464d1228aa1c373c5961324a0b1bd381521051b21c1e8c569ab96dda
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:52f9aa160bdd748f3bf7df52130ff965bec20e0a3f366bdbb7d88736b1c2c79a
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:52f9aa160bdd748f3bf7df52130ff965bec20e0a3f366bdbb7d88736b1c2c79a
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/strimzi/operator@sha256:52f9aa160bdd748f3bf7df52130ff965bec20e0a3f366bdbb7d88736b1c2c79a
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge@sha256:4ba0d4d7244df8a490b966cfdc72cab9e5ec400623928df7e16146cd01a80edd
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: quay.io/strimzi/jmxtrans@sha256:ea4ed242d4c9675e8cf92df44c9ab8b76a9cbe335914f7b8156cd73fe5589507
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: quay.io/strimzi/kaniko-executor@sha256:544c4987f7f3ca558b04e9ef4357be204f088212b7b5b9ed0f909401a8bc5238
            - name: STRIMZI_DEFAULT_MAVEN_BUILDER
              value: quay.io/strimzi/maven-builder@sha256:7d1c3a2bbfd6a4c5afd86073d1dccc98eba61e915108e68034bbb3c9ea3596dc
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FEATURE_GATES
              value: "+UseStrimziPodSets"
            - name: STRIMZI_LOG_LEVEL
              value: "DEBUG"
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 384Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodetype
                    operator: In
                    values:
                      - infra
  strategy:
    type: Recreate
