apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: co-config-volume
          configMap:
            name: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/strimzi/operator@sha256:1a69dbf509b82947e12e6544353663a53ad287cd9e127ab0d4b70e9ad1f2b177
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              # we want to have cluster-wide operator
              value: "*"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: quay.io/strimzi/kafka@sha256:3d2571ec9ba3028f4e2781b537fb3615b448c6c9f444fa514e508de707791dc4
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: quay.io/strimzi/kafka@sha256:3d2571ec9ba3028f4e2781b537fb3615b448c6c9f444fa514e508de707791dc4
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:3d2571ec9ba3028f4e2781b537fb3615b448c6c9f444fa514e508de707791dc4
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:3d2571ec9ba3028f4e2781b537fb3615b448c6c9f444fa514e508de707791dc4
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:93f3a5f7618b02058bb8ccb2b06b5a08827e0f9ab72beef872b0eeca2397f778
                3.1.0=quay.io/strimzi/kafka@sha256:3d2571ec9ba3028f4e2781b537fb3615b448c6c9f444fa514e508de707791dc4
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:93f3a5f7618b02058bb8ccb2b06b5a08827e0f9ab72beef872b0eeca2397f778
                3.1.0=quay.io/strimzi/kafka@sha256:3d2571ec9ba3028f4e2781b537fb3615b448c6c9f444fa514e508de707791dc4
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:93f3a5f7618b02058bb8ccb2b06b5a08827e0f9ab72beef872b0eeca2397f778
                3.1.0=quay.io/strimzi/kafka@sha256:3d2571ec9ba3028f4e2781b537fb3615b448c6c9f444fa514e508de707791dc4
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:93f3a5f7618b02058bb8ccb2b06b5a08827e0f9ab72beef872b0eeca2397f778
                3.1.0=quay.io/strimzi/kafka@sha256:3d2571ec9ba3028f4e2781b537fb3615b448c6c9f444fa514e508de707791dc4
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:1a69dbf509b82947e12e6544353663a53ad287cd9e127ab0d4b70e9ad1f2b177
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:1a69dbf509b82947e12e6544353663a53ad287cd9e127ab0d4b70e9ad1f2b177
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/strimzi/operator@sha256:1a69dbf509b82947e12e6544353663a53ad287cd9e127ab0d4b70e9ad1f2b177
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge@sha256:1e7ac03ca7350586d7a34ca510535c3a813c5635fe78b95cb70b91d8183aeea2
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: quay.io/strimzi/jmxtrans@sha256:8ce454c09092d1131a7fb972207739c97563c42858412bfa21071f4103363a33
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: quay.io/strimzi/kaniko-executor@sha256:a07ebe6600d6baba09980abdde2931b3b6abd2f75aeb2cac5c6a2d22a37aa807
            - name: STRIMZI_DEFAULT_MAVEN_BUILDER
              value: quay.io/strimzi/maven-builder@sha256:9f6485be360557b629e5ca393ac15fb6a8d88a8d83435ee6636a48b7ddc822f7
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FEATURE_GATES
              value: ""
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 384Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodetype
                    operator: In
                    values:
                      - infra
  strategy:
    type: Recreate
