apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: co-config-volume
          configMap:
            name: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/strimzi/operator@sha256:dcf4179a96826e59db3e2385b9f53251d42d0e949a7e356207b782c207ec0623
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              # we want to have cluster-wide operator
              value: "*"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: quay.io/strimzi/kafka@sha256:401a0f45708c1cec035f3e539153b751b30f04ce7cf2ef49741cfaae35b448cd
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: quay.io/strimzi/kafka@sha256:401a0f45708c1cec035f3e539153b751b30f04ce7cf2ef49741cfaae35b448cd
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:401a0f45708c1cec035f3e539153b751b30f04ce7cf2ef49741cfaae35b448cd
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                3.1.0=quay.io/strimzi/kafka@sha256:67fc185e810f53b9ed428ecda97b6f0413db58db7b4fbe375ac61e737360f55c
                3.1.1=quay.io/strimzi/kafka@sha256:998a2c98ec0c252151a54aa27aef46586eecfde7cf0bc8898a559a4d6b4a527e
                3.2.0=quay.io/strimzi/kafka@sha256:401a0f45708c1cec035f3e539153b751b30f04ce7cf2ef49741cfaae35b448cd
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                3.1.0=quay.io/strimzi/kafka@sha256:67fc185e810f53b9ed428ecda97b6f0413db58db7b4fbe375ac61e737360f55c
                3.1.1=quay.io/strimzi/kafka@sha256:998a2c98ec0c252151a54aa27aef46586eecfde7cf0bc8898a559a4d6b4a527e
                3.2.0=quay.io/strimzi/kafka@sha256:401a0f45708c1cec035f3e539153b751b30f04ce7cf2ef49741cfaae35b448cd
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                3.1.0=quay.io/strimzi/kafka@sha256:67fc185e810f53b9ed428ecda97b6f0413db58db7b4fbe375ac61e737360f55c
                3.1.1=quay.io/strimzi/kafka@sha256:998a2c98ec0c252151a54aa27aef46586eecfde7cf0bc8898a559a4d6b4a527e
                3.2.0=quay.io/strimzi/kafka@sha256:401a0f45708c1cec035f3e539153b751b30f04ce7cf2ef49741cfaae35b448cd
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                3.1.0=quay.io/strimzi/kafka@sha256:67fc185e810f53b9ed428ecda97b6f0413db58db7b4fbe375ac61e737360f55c
                3.1.1=quay.io/strimzi/kafka@sha256:998a2c98ec0c252151a54aa27aef46586eecfde7cf0bc8898a559a4d6b4a527e
                3.2.0=quay.io/strimzi/kafka@sha256:401a0f45708c1cec035f3e539153b751b30f04ce7cf2ef49741cfaae35b448cd
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:dcf4179a96826e59db3e2385b9f53251d42d0e949a7e356207b782c207ec0623
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:dcf4179a96826e59db3e2385b9f53251d42d0e949a7e356207b782c207ec0623
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/strimzi/operator@sha256:dcf4179a96826e59db3e2385b9f53251d42d0e949a7e356207b782c207ec0623
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge@sha256:b6a2fddfc8f014c94878b6f5b0df5bffa8c380134d65b46bd5011ad53bd39435
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: quay.io/strimzi/jmxtrans@sha256:1c301cce138dfdb0a3de122ce4fd21c6a287cbed82742dce902fcd9dc49e9cf2
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: quay.io/strimzi/kaniko-executor@sha256:544c4987f7f3ca558b04e9ef4357be204f088212b7b5b9ed0f909401a8bc5238
            - name: STRIMZI_DEFAULT_MAVEN_BUILDER
              value: quay.io/strimzi/maven-builder@sha256:e7a0cc123ad88a9ccb5a57efd35f820d7d5897a2d6336dc1eea6c2cfed9214ca
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FEATURE_GATES
              value: "+UseStrimziPodSets"
            - name: STRIMZI_LOG_LEVEL
              value: "DEBUG"
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 384Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodetype
                    operator: In
                    values:
                      - infra
  strategy:
    type: Recreate
