apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: co-config-volume
          configMap:
            name: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/strimzi/operator@sha256:be0d537b3aa33cb548a8b2a4373b6680b8b9a543635923258890dd285ac5165e
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              # we want to have cluster-wide operator
              value: "*"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: quay.io/strimzi/kafka@sha256:df45e6cc83ab7dc32e02b5f23288c97c57326fd3e57373673a70f65ed8a36447
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: quay.io/strimzi/kafka@sha256:df45e6cc83ab7dc32e02b5f23288c97c57326fd3e57373673a70f65ed8a36447
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:df45e6cc83ab7dc32e02b5f23288c97c57326fd3e57373673a70f65ed8a36447
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:df45e6cc83ab7dc32e02b5f23288c97c57326fd3e57373673a70f65ed8a36447
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:6b271fa767ceef77c916df5f0e09d6befaa96e4729378fcc05568d0fe12ffcd8
                3.0.1=quay.io/strimzi/kafka@sha256:9ac388214f2490c2d8e5920a6cc383d360f77f3e93d33e9ab1dee090e8096ce5
                3.1.0=quay.io/strimzi/kafka@sha256:df45e6cc83ab7dc32e02b5f23288c97c57326fd3e57373673a70f65ed8a36447
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:6b271fa767ceef77c916df5f0e09d6befaa96e4729378fcc05568d0fe12ffcd8
                3.0.1=quay.io/strimzi/kafka@sha256:9ac388214f2490c2d8e5920a6cc383d360f77f3e93d33e9ab1dee090e8096ce5
                3.1.0=quay.io/strimzi/kafka@sha256:df45e6cc83ab7dc32e02b5f23288c97c57326fd3e57373673a70f65ed8a36447
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:6b271fa767ceef77c916df5f0e09d6befaa96e4729378fcc05568d0fe12ffcd8
                3.0.1=quay.io/strimzi/kafka@sha256:9ac388214f2490c2d8e5920a6cc383d360f77f3e93d33e9ab1dee090e8096ce5
                3.1.0=quay.io/strimzi/kafka@sha256:df45e6cc83ab7dc32e02b5f23288c97c57326fd3e57373673a70f65ed8a36447
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:6b271fa767ceef77c916df5f0e09d6befaa96e4729378fcc05568d0fe12ffcd8
                3.0.1=quay.io/strimzi/kafka@sha256:9ac388214f2490c2d8e5920a6cc383d360f77f3e93d33e9ab1dee090e8096ce5
                3.1.0=quay.io/strimzi/kafka@sha256:df45e6cc83ab7dc32e02b5f23288c97c57326fd3e57373673a70f65ed8a36447
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:be0d537b3aa33cb548a8b2a4373b6680b8b9a543635923258890dd285ac5165e
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:be0d537b3aa33cb548a8b2a4373b6680b8b9a543635923258890dd285ac5165e
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/strimzi/operator@sha256:be0d537b3aa33cb548a8b2a4373b6680b8b9a543635923258890dd285ac5165e
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge@sha256:cbaa086a0466b6a3130bbe8a241950e7a23b75329bfa661a9678204e176f1938
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: quay.io/strimzi/jmxtrans@sha256:5b2906a77267b930fd67597b6b33f82839aec8b4d3efcfba047989a033be8897
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: quay.io/strimzi/kaniko-executor@sha256:f17e8ee327ca966f82bac6a0a2ba2f7fa50dba1418b2a4c93740b809c40fce41
            - name: STRIMZI_DEFAULT_MAVEN_BUILDER
              value: quay.io/strimzi/maven-builder@sha256:f5613c1efee21c3f18899be8866906305644a06933e596146862f042b4b1a4f4
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FEATURE_GATES
              value: ""
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 384Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodetype
                    operator: In
                    values:
                      - infra
  strategy:
    type: Recreate
