apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: co-config-volume
          configMap:
            name: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/strimzi/operator@sha256:76039384c1663796af5636342bd564a8ef8ba928893390f1a4cea1d5b0f819cf
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              # we want to have cluster-wide operator
              value: "*"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: quay.io/strimzi/kafka@sha256:a30c552f7358578e8b1b1131cfa49bb93bac04d0422563083537e16c7e6db4c3
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: quay.io/strimzi/kafka@sha256:a30c552f7358578e8b1b1131cfa49bb93bac04d0422563083537e16c7e6db4c3
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:a30c552f7358578e8b1b1131cfa49bb93bac04d0422563083537e16c7e6db4c3
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:bd3bbae8c8baa150e5504f8c4a6782a24788fe61cd63c47b3b41a0af55ebd863
                3.0.1=quay.io/strimzi/kafka@sha256:fef880c080c45884b12b7f40f724eb136d76e3106781c1b289d61df45e4747fd
                3.1.0=quay.io/strimzi/kafka@sha256:a30c552f7358578e8b1b1131cfa49bb93bac04d0422563083537e16c7e6db4c3
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:bd3bbae8c8baa150e5504f8c4a6782a24788fe61cd63c47b3b41a0af55ebd863
                3.0.1=quay.io/strimzi/kafka@sha256:fef880c080c45884b12b7f40f724eb136d76e3106781c1b289d61df45e4747fd
                3.1.0=quay.io/strimzi/kafka@sha256:a30c552f7358578e8b1b1131cfa49bb93bac04d0422563083537e16c7e6db4c3
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:bd3bbae8c8baa150e5504f8c4a6782a24788fe61cd63c47b3b41a0af55ebd863
                3.0.1=quay.io/strimzi/kafka@sha256:fef880c080c45884b12b7f40f724eb136d76e3106781c1b289d61df45e4747fd
                3.1.0=quay.io/strimzi/kafka@sha256:a30c552f7358578e8b1b1131cfa49bb93bac04d0422563083537e16c7e6db4c3
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:bd3bbae8c8baa150e5504f8c4a6782a24788fe61cd63c47b3b41a0af55ebd863
                3.0.1=quay.io/strimzi/kafka@sha256:fef880c080c45884b12b7f40f724eb136d76e3106781c1b289d61df45e4747fd
                3.1.0=quay.io/strimzi/kafka@sha256:a30c552f7358578e8b1b1131cfa49bb93bac04d0422563083537e16c7e6db4c3
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:76039384c1663796af5636342bd564a8ef8ba928893390f1a4cea1d5b0f819cf
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:76039384c1663796af5636342bd564a8ef8ba928893390f1a4cea1d5b0f819cf
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/strimzi/operator@sha256:76039384c1663796af5636342bd564a8ef8ba928893390f1a4cea1d5b0f819cf
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge@sha256:7ee70a2944cb82c46826e9dcbf167a5dc52ddf797e86de3f0a7c8f656eaa256b
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: quay.io/strimzi/jmxtrans@sha256:a463b36bda8ab7dc35c5df3645f34ec5cf0cb3a9ac175596f55754f9da302f02
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: quay.io/strimzi/kaniko-executor@sha256:544c4987f7f3ca558b04e9ef4357be204f088212b7b5b9ed0f909401a8bc5238
            - name: STRIMZI_DEFAULT_MAVEN_BUILDER
              value: quay.io/strimzi/maven-builder@sha256:fa79f74043a0b1f68ba3e36d8a8b80ddc7a9fb67456419cbfe88dd0b6efe855e
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FEATURE_GATES
              value: "+UseStrimziPodSets"
            - name: STRIMZI_LOG_LEVEL
              value: "DEBUG"
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 384Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodetype
                    operator: In
                    values:
                      - infra
  strategy:
    type: Recreate
