apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: co-config-volume
          configMap:
            name: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/strimzi/operator@sha256:48b8a4d470fdd52bfb3058120efddbcaa8ef13053807c5474e66e8e25f8af0bb
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              # we want to have cluster-wide operator
              value: "*"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: quay.io/strimzi/kafka@sha256:ef5cf96ff5af055e69392c6256eb94b412b28f72a1f9ce3aef1d21b16b116ce2
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: quay.io/strimzi/kafka@sha256:ef5cf96ff5af055e69392c6256eb94b412b28f72a1f9ce3aef1d21b16b116ce2
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:ef5cf96ff5af055e69392c6256eb94b412b28f72a1f9ce3aef1d21b16b116ce2
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:5ee733807f0226e357b4ec55f3af8a8b3e77a15001efb00e3c22870a497c460d
                3.0.1=quay.io/strimzi/kafka@sha256:fa330ceb540c6a82a7c59ee2ca5a40d381561d816746a8ecc5e11ab5d1923961
                3.1.0=quay.io/strimzi/kafka@sha256:ef5cf96ff5af055e69392c6256eb94b412b28f72a1f9ce3aef1d21b16b116ce2
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:5ee733807f0226e357b4ec55f3af8a8b3e77a15001efb00e3c22870a497c460d
                3.0.1=quay.io/strimzi/kafka@sha256:fa330ceb540c6a82a7c59ee2ca5a40d381561d816746a8ecc5e11ab5d1923961
                3.1.0=quay.io/strimzi/kafka@sha256:ef5cf96ff5af055e69392c6256eb94b412b28f72a1f9ce3aef1d21b16b116ce2
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:5ee733807f0226e357b4ec55f3af8a8b3e77a15001efb00e3c22870a497c460d
                3.0.1=quay.io/strimzi/kafka@sha256:fa330ceb540c6a82a7c59ee2ca5a40d381561d816746a8ecc5e11ab5d1923961
                3.1.0=quay.io/strimzi/kafka@sha256:ef5cf96ff5af055e69392c6256eb94b412b28f72a1f9ce3aef1d21b16b116ce2
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:5ee733807f0226e357b4ec55f3af8a8b3e77a15001efb00e3c22870a497c460d
                3.0.1=quay.io/strimzi/kafka@sha256:fa330ceb540c6a82a7c59ee2ca5a40d381561d816746a8ecc5e11ab5d1923961
                3.1.0=quay.io/strimzi/kafka@sha256:ef5cf96ff5af055e69392c6256eb94b412b28f72a1f9ce3aef1d21b16b116ce2
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:48b8a4d470fdd52bfb3058120efddbcaa8ef13053807c5474e66e8e25f8af0bb
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:48b8a4d470fdd52bfb3058120efddbcaa8ef13053807c5474e66e8e25f8af0bb
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/strimzi/operator@sha256:48b8a4d470fdd52bfb3058120efddbcaa8ef13053807c5474e66e8e25f8af0bb
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge@sha256:4ba0d4d7244df8a490b966cfdc72cab9e5ec400623928df7e16146cd01a80edd
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: quay.io/strimzi/jmxtrans@sha256:20c084c3f689658e3f11d5f532d85f95a89d035e8d68fa3e607796ee532f5f8e
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: quay.io/strimzi/kaniko-executor@sha256:544c4987f7f3ca558b04e9ef4357be204f088212b7b5b9ed0f909401a8bc5238
            - name: STRIMZI_DEFAULT_MAVEN_BUILDER
              value: quay.io/strimzi/maven-builder@sha256:dfba2d8c1c527003076f6d5b38a08a5778a51bf32487493b271e94dd41a20112
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FEATURE_GATES
              value: "+UseStrimziPodSets"
            - name: STRIMZI_LOG_LEVEL
              value: "DEBUG"
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 384Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodetype
                    operator: In
                    values:
                      - infra
  strategy:
    type: Recreate
