apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: co-config-volume
          configMap:
            name: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/strimzi/operator@sha256:80825a520fdb21662f182287320516007e7e68da87a1fd7ba708d7ea5f648657
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              # we want to have cluster-wide operator
              value: "*"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: quay.io/strimzi/kafka@sha256:3d0fcca2167bca0bd6d6b33a53970a898f551c0050eafa744f426bb713d5deca
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: quay.io/strimzi/kafka@sha256:3d0fcca2167bca0bd6d6b33a53970a898f551c0050eafa744f426bb713d5deca
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:3d0fcca2167bca0bd6d6b33a53970a898f551c0050eafa744f426bb713d5deca
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:a8dee54fc976676184312e51002c7fd6c49b31f99677e6282ff719913ee0a151
                3.0.1=quay.io/strimzi/kafka@sha256:449b42f3d6dbb0afdba09a086d80415a2008421c8714684147f3d5ee6cc29eb8
                3.1.0=quay.io/strimzi/kafka@sha256:3d0fcca2167bca0bd6d6b33a53970a898f551c0050eafa744f426bb713d5deca
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:a8dee54fc976676184312e51002c7fd6c49b31f99677e6282ff719913ee0a151
                3.0.1=quay.io/strimzi/kafka@sha256:449b42f3d6dbb0afdba09a086d80415a2008421c8714684147f3d5ee6cc29eb8
                3.1.0=quay.io/strimzi/kafka@sha256:3d0fcca2167bca0bd6d6b33a53970a898f551c0050eafa744f426bb713d5deca
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:a8dee54fc976676184312e51002c7fd6c49b31f99677e6282ff719913ee0a151
                3.0.1=quay.io/strimzi/kafka@sha256:449b42f3d6dbb0afdba09a086d80415a2008421c8714684147f3d5ee6cc29eb8
                3.1.0=quay.io/strimzi/kafka@sha256:3d0fcca2167bca0bd6d6b33a53970a898f551c0050eafa744f426bb713d5deca
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:a8dee54fc976676184312e51002c7fd6c49b31f99677e6282ff719913ee0a151
                3.0.1=quay.io/strimzi/kafka@sha256:449b42f3d6dbb0afdba09a086d80415a2008421c8714684147f3d5ee6cc29eb8
                3.1.0=quay.io/strimzi/kafka@sha256:3d0fcca2167bca0bd6d6b33a53970a898f551c0050eafa744f426bb713d5deca
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:80825a520fdb21662f182287320516007e7e68da87a1fd7ba708d7ea5f648657
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:80825a520fdb21662f182287320516007e7e68da87a1fd7ba708d7ea5f648657
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/strimzi/operator@sha256:80825a520fdb21662f182287320516007e7e68da87a1fd7ba708d7ea5f648657
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge@sha256:b1bfd695b7e45c399a5699dc68c1406e6f5d1cda0a30fc8cdb9648c91cbbe895
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: quay.io/strimzi/jmxtrans@sha256:da5804698d0ce8992ccadca864fc32f47bb8733aa4502e08e47f6b626b2d5fbf
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: quay.io/strimzi/kaniko-executor@sha256:544c4987f7f3ca558b04e9ef4357be204f088212b7b5b9ed0f909401a8bc5238
            - name: STRIMZI_DEFAULT_MAVEN_BUILDER
              value: quay.io/strimzi/maven-builder@sha256:5b525bc5b01719797f0f22309eeb07f022a4d4a44dafc1d23de7c313dedf4176
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FEATURE_GATES
              value: "+UseStrimziPodSets"
            - name: STRIMZI_LOG_LEVEL
              value: "DEBUG"
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 384Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodetype
                    operator: In
                    values:
                      - infra
  strategy:
    type: Recreate
