apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: co-config-volume
          configMap:
            name: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/strimzi/operator@sha256:a037748c43df60085ef55d1b2fee0a347745f964ca8aeaea705a4aff8e66390b
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              # we want to have cluster-wide operator
              value: "*"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: quay.io/strimzi/kafka@sha256:d57bcfd36de4e6571bc4ac461f3e1cbb104f352cf1ad89390547ea13dc5efdb6
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: quay.io/strimzi/kafka@sha256:d57bcfd36de4e6571bc4ac461f3e1cbb104f352cf1ad89390547ea13dc5efdb6
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:d57bcfd36de4e6571bc4ac461f3e1cbb104f352cf1ad89390547ea13dc5efdb6
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                3.1.0=quay.io/strimzi/kafka@sha256:f51dc22f183eac0a191d44f5160137dc159f11cecfe32d7db5820f28be9bc855
                3.1.1=quay.io/strimzi/kafka@sha256:5f28d2d019fe436bf0d8d22fa1f5476d10efbd15605f38d0b6af7f57b9ba0f24
                3.2.0=quay.io/strimzi/kafka@sha256:d57bcfd36de4e6571bc4ac461f3e1cbb104f352cf1ad89390547ea13dc5efdb6
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                3.1.0=quay.io/strimzi/kafka@sha256:f51dc22f183eac0a191d44f5160137dc159f11cecfe32d7db5820f28be9bc855
                3.1.1=quay.io/strimzi/kafka@sha256:5f28d2d019fe436bf0d8d22fa1f5476d10efbd15605f38d0b6af7f57b9ba0f24
                3.2.0=quay.io/strimzi/kafka@sha256:d57bcfd36de4e6571bc4ac461f3e1cbb104f352cf1ad89390547ea13dc5efdb6
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                3.1.0=quay.io/strimzi/kafka@sha256:f51dc22f183eac0a191d44f5160137dc159f11cecfe32d7db5820f28be9bc855
                3.1.1=quay.io/strimzi/kafka@sha256:5f28d2d019fe436bf0d8d22fa1f5476d10efbd15605f38d0b6af7f57b9ba0f24
                3.2.0=quay.io/strimzi/kafka@sha256:d57bcfd36de4e6571bc4ac461f3e1cbb104f352cf1ad89390547ea13dc5efdb6
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                3.1.0=quay.io/strimzi/kafka@sha256:f51dc22f183eac0a191d44f5160137dc159f11cecfe32d7db5820f28be9bc855
                3.1.1=quay.io/strimzi/kafka@sha256:5f28d2d019fe436bf0d8d22fa1f5476d10efbd15605f38d0b6af7f57b9ba0f24
                3.2.0=quay.io/strimzi/kafka@sha256:d57bcfd36de4e6571bc4ac461f3e1cbb104f352cf1ad89390547ea13dc5efdb6
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:a037748c43df60085ef55d1b2fee0a347745f964ca8aeaea705a4aff8e66390b
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:a037748c43df60085ef55d1b2fee0a347745f964ca8aeaea705a4aff8e66390b
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/strimzi/operator@sha256:a037748c43df60085ef55d1b2fee0a347745f964ca8aeaea705a4aff8e66390b
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge@sha256:af8504d7f0b462c820fabc914b4e04ce49a18c39a6e2168ac62effe7e2e34edb
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: quay.io/strimzi/jmxtrans@sha256:60c1b4035537b880390d8389175ad8b5da509e2648159a695691ad22710fa9c6
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: quay.io/strimzi/kaniko-executor@sha256:544c4987f7f3ca558b04e9ef4357be204f088212b7b5b9ed0f909401a8bc5238
            - name: STRIMZI_DEFAULT_MAVEN_BUILDER
              value: quay.io/strimzi/maven-builder@sha256:087e3609bf02e087b7676feb6573cf6418155a024462804a02603b2b5a37d746
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FEATURE_GATES
              value: "+UseStrimziPodSets"
            - name: STRIMZI_LOG_LEVEL
              value: "DEBUG"
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 384Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodetype
                    operator: In
                    values:
                      - infra
  strategy:
    type: Recreate
