apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: co-config-volume
          configMap:
            name: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/strimzi/operator@sha256:25593e9b4468fe076d34ac8570af536e549561b7cafde67519933778887d87fc
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              # we want to have cluster-wide operator
              value: "*"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: quay.io/strimzi/kafka@sha256:711e743b11512f652b0be3bc6b13bbe68ca4f40ec52a5e021f977936f8e550c0
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: quay.io/strimzi/kafka@sha256:711e743b11512f652b0be3bc6b13bbe68ca4f40ec52a5e021f977936f8e550c0
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:711e743b11512f652b0be3bc6b13bbe68ca4f40ec52a5e021f977936f8e550c0
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:711e743b11512f652b0be3bc6b13bbe68ca4f40ec52a5e021f977936f8e550c0
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:feb4c25e40c97bb682851948f0ead17eae57b5cd201fbb39f651a90fab5a1341
                3.1.0=quay.io/strimzi/kafka@sha256:711e743b11512f652b0be3bc6b13bbe68ca4f40ec52a5e021f977936f8e550c0
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:feb4c25e40c97bb682851948f0ead17eae57b5cd201fbb39f651a90fab5a1341
                3.1.0=quay.io/strimzi/kafka@sha256:711e743b11512f652b0be3bc6b13bbe68ca4f40ec52a5e021f977936f8e550c0
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:feb4c25e40c97bb682851948f0ead17eae57b5cd201fbb39f651a90fab5a1341
                3.1.0=quay.io/strimzi/kafka@sha256:711e743b11512f652b0be3bc6b13bbe68ca4f40ec52a5e021f977936f8e550c0
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:feb4c25e40c97bb682851948f0ead17eae57b5cd201fbb39f651a90fab5a1341
                3.1.0=quay.io/strimzi/kafka@sha256:711e743b11512f652b0be3bc6b13bbe68ca4f40ec52a5e021f977936f8e550c0
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:25593e9b4468fe076d34ac8570af536e549561b7cafde67519933778887d87fc
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:25593e9b4468fe076d34ac8570af536e549561b7cafde67519933778887d87fc
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/strimzi/operator@sha256:25593e9b4468fe076d34ac8570af536e549561b7cafde67519933778887d87fc
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge@sha256:1e7ac03ca7350586d7a34ca510535c3a813c5635fe78b95cb70b91d8183aeea2
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: quay.io/strimzi/jmxtrans@sha256:b903128c94799ecbce35545d237d60072f6e27d17306aca1ff34041bb30414c7
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: quay.io/strimzi/kaniko-executor@sha256:a07ebe6600d6baba09980abdde2931b3b6abd2f75aeb2cac5c6a2d22a37aa807
            - name: STRIMZI_DEFAULT_MAVEN_BUILDER
              value: quay.io/strimzi/maven-builder@sha256:abd8f49a84f3531573dda139ad763049a9e14ebd4758b460ebc60baca59eb72e
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FEATURE_GATES
              value: ""
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 384Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodetype
                    operator: In
                    values:
                      - infra
  strategy:
    type: Recreate
