apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: co-config-volume
          configMap:
            name: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/strimzi/operator@sha256:5589a2a48685ad0f60c92ce55588b16cf9a89a4e3b2b8c40eccd56435d16ae19
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              # we want to have cluster-wide operator
              value: "*"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: quay.io/strimzi/kafka@sha256:3d1f5af0108f8a6b0d3ddb69ed2dda866b6d4b3c14f394416c0005f3b4fa94ec
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: quay.io/strimzi/kafka@sha256:3d1f5af0108f8a6b0d3ddb69ed2dda866b6d4b3c14f394416c0005f3b4fa94ec
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:3d1f5af0108f8a6b0d3ddb69ed2dda866b6d4b3c14f394416c0005f3b4fa94ec
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:5ffd8f4cf8b6aca0a2a0a5c80736bd67e01a6cc665392f52dcb02f1fc4443398
                3.0.1=quay.io/strimzi/kafka@sha256:1a9ac22936ff435840383209c969a488e20e061a9adfce91d988e9dbdd510a4a
                3.1.0=quay.io/strimzi/kafka@sha256:3d1f5af0108f8a6b0d3ddb69ed2dda866b6d4b3c14f394416c0005f3b4fa94ec
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:5ffd8f4cf8b6aca0a2a0a5c80736bd67e01a6cc665392f52dcb02f1fc4443398
                3.0.1=quay.io/strimzi/kafka@sha256:1a9ac22936ff435840383209c969a488e20e061a9adfce91d988e9dbdd510a4a
                3.1.0=quay.io/strimzi/kafka@sha256:3d1f5af0108f8a6b0d3ddb69ed2dda866b6d4b3c14f394416c0005f3b4fa94ec
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:5ffd8f4cf8b6aca0a2a0a5c80736bd67e01a6cc665392f52dcb02f1fc4443398
                3.0.1=quay.io/strimzi/kafka@sha256:1a9ac22936ff435840383209c969a488e20e061a9adfce91d988e9dbdd510a4a
                3.1.0=quay.io/strimzi/kafka@sha256:3d1f5af0108f8a6b0d3ddb69ed2dda866b6d4b3c14f394416c0005f3b4fa94ec
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:5ffd8f4cf8b6aca0a2a0a5c80736bd67e01a6cc665392f52dcb02f1fc4443398
                3.0.1=quay.io/strimzi/kafka@sha256:1a9ac22936ff435840383209c969a488e20e061a9adfce91d988e9dbdd510a4a
                3.1.0=quay.io/strimzi/kafka@sha256:3d1f5af0108f8a6b0d3ddb69ed2dda866b6d4b3c14f394416c0005f3b4fa94ec
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:5589a2a48685ad0f60c92ce55588b16cf9a89a4e3b2b8c40eccd56435d16ae19
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:5589a2a48685ad0f60c92ce55588b16cf9a89a4e3b2b8c40eccd56435d16ae19
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/strimzi/operator@sha256:5589a2a48685ad0f60c92ce55588b16cf9a89a4e3b2b8c40eccd56435d16ae19
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge@sha256:a1fbe9e309fac8324c96f19667f4d9837266e7d79fcd8da85976930a3d90444b
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: quay.io/strimzi/jmxtrans@sha256:59c8c07a223293b0cc075c252761d40e8f80c2bb5bec0adc3c6cb2b347393d7d
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: quay.io/strimzi/kaniko-executor@sha256:544c4987f7f3ca558b04e9ef4357be204f088212b7b5b9ed0f909401a8bc5238
            - name: STRIMZI_DEFAULT_MAVEN_BUILDER
              value: quay.io/strimzi/maven-builder@sha256:92847d8b85a20552a9eaa02897967308651a3bad36ca2b2fef6065b8b3aa53d2
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FEATURE_GATES
              value: "+UseStrimziPodSets"
            - name: STRIMZI_LOG_LEVEL
              value: "DEBUG"
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 384Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodetype
                    operator: In
                    values:
                      - infra
  strategy:
    type: Recreate
