apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: co-config-volume
          configMap:
            name: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/strimzi/operator@sha256:d421dfb7242eea5e6e6aa46d05e3ce9cabd81dca016fc47bda10fecae2912fab
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              # we want to have cluster-wide operator
              value: "*"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: quay.io/strimzi/kafka@sha256:361b91594ad6fd5778dc22755db9b2ce9bf584cb1bc6265a0aaa7cf8a4c87a96
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: quay.io/strimzi/kafka@sha256:361b91594ad6fd5778dc22755db9b2ce9bf584cb1bc6265a0aaa7cf8a4c87a96
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:361b91594ad6fd5778dc22755db9b2ce9bf584cb1bc6265a0aaa7cf8a4c87a96
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:fdea45fedafc747bec315e2eaa725e3799010b6c6926e964f62cfbf5c3095719
                3.0.1=quay.io/strimzi/kafka@sha256:08e3806a6270970028f0f2e95489d2fa1346c73b9d6186d68b55082e67c9dfd8
                3.1.0=quay.io/strimzi/kafka@sha256:361b91594ad6fd5778dc22755db9b2ce9bf584cb1bc6265a0aaa7cf8a4c87a96
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:fdea45fedafc747bec315e2eaa725e3799010b6c6926e964f62cfbf5c3095719
                3.0.1=quay.io/strimzi/kafka@sha256:08e3806a6270970028f0f2e95489d2fa1346c73b9d6186d68b55082e67c9dfd8
                3.1.0=quay.io/strimzi/kafka@sha256:361b91594ad6fd5778dc22755db9b2ce9bf584cb1bc6265a0aaa7cf8a4c87a96
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:fdea45fedafc747bec315e2eaa725e3799010b6c6926e964f62cfbf5c3095719
                3.0.1=quay.io/strimzi/kafka@sha256:08e3806a6270970028f0f2e95489d2fa1346c73b9d6186d68b55082e67c9dfd8
                3.1.0=quay.io/strimzi/kafka@sha256:361b91594ad6fd5778dc22755db9b2ce9bf584cb1bc6265a0aaa7cf8a4c87a96
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:fdea45fedafc747bec315e2eaa725e3799010b6c6926e964f62cfbf5c3095719
                3.0.1=quay.io/strimzi/kafka@sha256:08e3806a6270970028f0f2e95489d2fa1346c73b9d6186d68b55082e67c9dfd8
                3.1.0=quay.io/strimzi/kafka@sha256:361b91594ad6fd5778dc22755db9b2ce9bf584cb1bc6265a0aaa7cf8a4c87a96
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:d421dfb7242eea5e6e6aa46d05e3ce9cabd81dca016fc47bda10fecae2912fab
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:d421dfb7242eea5e6e6aa46d05e3ce9cabd81dca016fc47bda10fecae2912fab
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/strimzi/operator@sha256:d421dfb7242eea5e6e6aa46d05e3ce9cabd81dca016fc47bda10fecae2912fab
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge@sha256:7ee70a2944cb82c46826e9dcbf167a5dc52ddf797e86de3f0a7c8f656eaa256b
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: quay.io/strimzi/jmxtrans@sha256:334bb17c2458256f6d84458b20df474f5514c2de6b4cb2c537df3a935b9cd36b
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: quay.io/strimzi/kaniko-executor@sha256:544c4987f7f3ca558b04e9ef4357be204f088212b7b5b9ed0f909401a8bc5238
            - name: STRIMZI_DEFAULT_MAVEN_BUILDER
              value: quay.io/strimzi/maven-builder@sha256:d28a0167ca93f32a796af252979ea509967ba816f9c5ea66e581b1fa4961ec51
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FEATURE_GATES
              value: "+UseStrimziPodSets"
            - name: STRIMZI_LOG_LEVEL
              value: "DEBUG"
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 384Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodetype
                    operator: In
                    values:
                      - infra
  strategy:
    type: Recreate
