apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: co-config-volume
          configMap:
            name: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/strimzi/operator@sha256:0c8c676fa3b0c1533ec5a6ae114d8195db35a22870d2af9c7403cce5bbbdbbaf
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              # we want to have cluster-wide operator
              value: "*"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: quay.io/strimzi/kafka@sha256:864f81a479ab1babc29d9c39ec2f6942e1c53e4269a0fce9d6887472ab69908b
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: quay.io/strimzi/kafka@sha256:864f81a479ab1babc29d9c39ec2f6942e1c53e4269a0fce9d6887472ab69908b
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka@sha256:864f81a479ab1babc29d9c39ec2f6942e1c53e4269a0fce9d6887472ab69908b
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:3d18bad39f7ae648d9cb8c4aa6abf63a7d786ac774413b5e23bef40a4f7953cc
                3.0.1=quay.io/strimzi/kafka@sha256:29e91529db75258fae348763c5e8b2f3b9f0249a7d9276032e0f32f409e07eb8
                3.1.0=quay.io/strimzi/kafka@sha256:864f81a479ab1babc29d9c39ec2f6942e1c53e4269a0fce9d6887472ab69908b
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:3d18bad39f7ae648d9cb8c4aa6abf63a7d786ac774413b5e23bef40a4f7953cc
                3.0.1=quay.io/strimzi/kafka@sha256:29e91529db75258fae348763c5e8b2f3b9f0249a7d9276032e0f32f409e07eb8
                3.1.0=quay.io/strimzi/kafka@sha256:864f81a479ab1babc29d9c39ec2f6942e1c53e4269a0fce9d6887472ab69908b
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:3d18bad39f7ae648d9cb8c4aa6abf63a7d786ac774413b5e23bef40a4f7953cc
                3.0.1=quay.io/strimzi/kafka@sha256:29e91529db75258fae348763c5e8b2f3b9f0249a7d9276032e0f32f409e07eb8
                3.1.0=quay.io/strimzi/kafka@sha256:864f81a479ab1babc29d9c39ec2f6942e1c53e4269a0fce9d6887472ab69908b
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka@sha256:3d18bad39f7ae648d9cb8c4aa6abf63a7d786ac774413b5e23bef40a4f7953cc
                3.0.1=quay.io/strimzi/kafka@sha256:29e91529db75258fae348763c5e8b2f3b9f0249a7d9276032e0f32f409e07eb8
                3.1.0=quay.io/strimzi/kafka@sha256:864f81a479ab1babc29d9c39ec2f6942e1c53e4269a0fce9d6887472ab69908b
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:0c8c676fa3b0c1533ec5a6ae114d8195db35a22870d2af9c7403cce5bbbdbbaf
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/strimzi/operator@sha256:0c8c676fa3b0c1533ec5a6ae114d8195db35a22870d2af9c7403cce5bbbdbbaf
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/strimzi/operator@sha256:0c8c676fa3b0c1533ec5a6ae114d8195db35a22870d2af9c7403cce5bbbdbbaf
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge@sha256:3d37609d645b9e78f68fc01f17bb11397e81066792a4186261076d922c754272
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: quay.io/strimzi/jmxtrans@sha256:78c59b7a2743796b6b4ac56b173bc08a87d5564dcbea2021443e2d2a0bc50506
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: quay.io/strimzi/kaniko-executor@sha256:544c4987f7f3ca558b04e9ef4357be204f088212b7b5b9ed0f909401a8bc5238
            - name: STRIMZI_DEFAULT_MAVEN_BUILDER
              value: quay.io/strimzi/maven-builder@sha256:bda47f73792159f3ad22287da1deb14c2e3f0a6546237d018e353e7c08de0824
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FEATURE_GATES
              value: "+UseStrimziPodSets"
            - name: STRIMZI_LOG_LEVEL
              value: "DEBUG"
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 384Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodetype
                    operator: In
                    values:
                      - infra
  strategy:
    type: Recreate
