apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaRebalance
metadata:
  name: heimdall-rebalance
  labels:
    strimzi.io/cluster: heimdall
# no goals specified, using the default goals from the Cruise Control configuration
spec: {}
