apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaRebalance
metadata:
  name: anubis-rebalance
  labels:
    strimzi.io/cluster: anubis
# no goals specified, using the default goals from the Cruise Control configuration
spec: {}
