name: Yamllint

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

jobs:
  yaml-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .github/lint-config.yaml
