apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: grafanadatasource
  namespace: strimzi-monitoring
spec:
  name: middleware.yaml
  datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
      basicAuth: false
      basicAuthUser: internal
      isDefault: true
      version: 1
      editable: true
      jsonData:
        tlsSkipVerify: true
        timeInterval: "5s"
        httpHeaderName1: "Authorization"
      secureJsonData:
        httpHeaderValue1: "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IlhXQ200X0VYNHVCd1ZhejNERzZGSjBkWFZ4UnYxMnVXSXYtWmpPM3NmTWMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJzdHJpbXppLW1vbml0b3JpbmciLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiZ3JhZmFuYS1zZXJ2aWNlYWNjb3VudC10b2tlbi04cmM5OCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJncmFmYW5hLXNlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMGJlMDFjNmItNTE4MS00ODdhLWI4MjYtYjY2NzQ3MjM5M2RlIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OnN0cmltemktbW9uaXRvcmluZzpncmFmYW5hLXNlcnZpY2VhY2NvdW50In0.tkdGyH7Ikbb065fX81JCezs40u5AMJEOb-ImxO0UkFdgylnbK23NOVMhUDCQ5KIaQwtsDq_fFnmcWPaT3a8RUzb2wWcfJpc0K4b-_p1HsQGPuPAwjXN2uWXECYydJqUxnJl9N3McojRSVnQfePFvOyhbUtdt3OXB-S3QxF6RmWsc5SHSkOA05BvOL2BjKhKA8zggeBFrZEE1QXcrscRNd18M_npi9bUl9z3J4XyGpBCRcRAdD6jApFoIhy8psP6jfEZ4jjToNzOK5uXwbOJhYneJtH_YyApRP3maWstYO1LjqjjKtUOoKm9iikZGgCGM_1qCaB9D4V0bFlMkQATTuE-C4LnDGxCuvOuqa-RNQLdLrkuL04dZOgUVkhJc9EWbiW3azrztHwDlrGb0_ZEshtsamXCoEQrRcNClGH1nhxPZiue1XM9DPmst7NZP0pMf8Wpw_I1YKApj0QyUKOdEmuejm_psZZBRRiUNI7-UX1imtLxTyDyg_e0bdwA2O1xxurzD0J08SwPqXsvA0y5TLWMKZN00ycs3WgKKrI4PXJ27eDXU1ELD_P26DQM-6CCDgn2fqW-fqWmOwvvhCctWdZrJsoUpusqxO3MFeFAdKgL_AmsR9jgupsSU3_IWaHYMXJpjtblrVuJwoM-z9JRwN0WxOwsjAiQ92tjwR1UprhM"
