---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: grafana
  namespace: strimzi-monitoring
  labels:
    app: strimzi
spec:
  host: grafana.strimzi-monitoring.apps.tealc-aws.strimzi.app-services-dev.net
  port:
    targetPort: 3000
  to:
    kind: Service
    name: grafana
    weight: 100
  wildcardPolicy: None
