apiVersion: v1
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
        access: proxy
        basicAuth: false
        withCredentials: false
        isDefault: true
        jsonData:
          timeInterval: 5s
          tlsSkipVerify: true
          httpHeaderName1: "Authorization"
        secureJsonData:
          httpHeaderValue1: "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Ild3YnVaVEpJLUFDYWxGaXIwM2dRTGdRLThzVkVxd0xGSi1kTUhxOXh6R2sifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJzdHJpbXppLW1vbml0b3JpbmciLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiZ3JhZmFuYS1zZXJ2aWNlYWNjb3VudC10b2tlbi12NGd6biIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJncmFmYW5hLXNlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYzkwZGI5YWEtYTY3ZS00YjViLTg4MTEtNzQwZjcxYzk2MGJjIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OnN0cmltemktbW9uaXRvcmluZzpncmFmYW5hLXNlcnZpY2VhY2NvdW50In0.d7Kt47pcg6PJEyow7EFLmwKkgd2JZbYok4gzmngNFBIXy0Omtjp3RleGN51B1QCFwFETyi9q7DFs3ve2a1herD8AmG5qdkO9r7BIqBc4XjjOLQP1N1JLPhsWUzYzdf09cubyJZulDzoS_TSk2xFeS2zznMfwO6XS4fFWoC2VFNze4mO1us0hEjIf66hUDyTA0B0HMzY8jfFcaZlXuu54ePkG9HvowV3nNAT1FOdT_GUYXXKTiv3GIBXvJ9IPKLF9EbZQm6UR4gl2633h25Vl0lO9-THKYbC5Ik55R6fEaXKdloZ8lK1O-WWfh9gN0TELDK2XrqO6hTELs-DPtRh7b_J50S1Qe97GLX3XIpjWKIiEiKpFTVOe_vJj4W9k7y2CPFuEm1XfL__vIvgouyDnr6eJmmWTahFvN_mr4XNnUj6JwllMdERVyxzfZZYGv94rztcBAYtryK_N47gMU5hTeoIF_l6s4ytatA_cXHybf9rql18E058qxR_lQM7tctEgL0mIwQjYjrWxPlW8fYF1QO9-tOqWSy_ydICeznnjhUAZI1SeumVBybscM7WBiDHjzoH5wo3rVHX1Fmq2CSvqO-A0jDYNLO1ym-NFUrmmsp_UMb_FATSiko1GLwtfnWeeSWPimD0zEuq9SnXnqNAs-bg-p5w-DjiIySBQTh7kBDE"
        editable: true
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: strimzi-monitoring
